import re
from logging import getLogger
from typing import Iterable

log = getLogger(__name__)


class ClassNameFactory:
    """
    A converter from strings to class names which ensures name uniqueness and validity.
    """

    RE_UNWANTED = re.compile(r"[^a-zA-Z0-9]")
    """
    Finds characters that are unwanted in class names for a given string.
    
    .. admonition:: Example
    
        .. code-block:: python
    
            >>> RE_UNWANTED.sub("", r"Jack-o'-Lantern")
            'JackoLantern'
    """

    RE_NUMBER = re.compile(r"^([0-9])")
    """
    Checks if a string starts with a number.
    
    .. admonition:: Example
    
        .. code-block:: python
    
            >>> RE_NUMBER.sub("N\1", r"67Statue")
            'N67Statue'
    """

    def __repr__(self):
        return f"<{self.__class__.__qualname__} ({len(self.used)} generated)>"

    def __init__(self):
        """
        Create a new :class:`.ClassNameFactory`.

        .. admonition:: Example

            .. code-block: python

                >>> factory = ClassNameFactory()
                >>> factory
                <ClassNameFactory (0 generated)>
        """

        self.used: set[str] = set()
        "Set of all the class names that were already generated by :meth:`.__call__`."

    def __call__(self, base: str, *suffixes: str) -> str:
        """
        Generate a class name from the given string.

        #. First, unwanted characters are removed using :attr:`.RE_UNWANTED`
        #. Then, if :attr:`.RE_NUMBER` detects that the name starts with a number, a ``N`` is prefixed to the name.
        #. Then, :attr:`.used` is checked to see if the name does not already exist, and if it does, each of the ``*suffixes`` are tried in order, followed by a counter starting at 2, until a unique name is found.

        .. admonition:: Example

            .. code-block:: python

                >>> factory = ClassNameFactory()
                >>> factory
                <ClassNameFactory (0 generated)>
                >>> factory("Jack-o'-Lantern")
                'JackoLantern'
                >>> factory("Jack-o'-Lantern")
                'JackoLantern2'
                >>> factory("Jack-o'-Lantern", "Block")
                'JackoLanternBlock'
                >>> factory("Jack-o'-Lantern", "Block")
                'JackoLantern3'
                >>> factory.used
                {'JackoLantern', 'JackoLantern2', 'JackoLanternBlock', 'JackoLantern3'}

        """
        log.debug("Making class name from: %r", base)

        base = self.RE_UNWANTED.sub("", base)
        base = self.RE_NUMBER.sub(r"N\1", base)

        if len(base) == 0:
            base = "Unnamed"

        log.debug("Tentative class name is: %r", base)

        suffixes = iter(suffixes)
        counter = 1
        name = base
        while name in self.used:
            try:
                suffix = next(suffixes)
            except StopIteration:
                counter += 1
                suffix = f"{counter}"
            log.debug("Tentative class name already exists, attempting to use suffix: %r", suffix)
            name = f"{base}{suffix}"
            log.debug("New tentative class name is: %r", name)

        log.info("Determined final class name: %r", name)
        self.used.add(name)
        return name


__all__ = ("ClassNameFactory",)
