[project]
name = "lihzahrd"
version = "4.0.0b2"
description = "Terraria world parser in Python"
authors = [
    {name = "Stefano Pigozzi", email = "me@steffo.eu"},
]
maintainers = [
    {name = "Stefano Pigozzi", email = "me@steffo.eu"},
]
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.md"]
readme = "README.md"
keywords = [
    "terraria",
    "parser",
    "game",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Natural Language :: English",
    "Topic :: Games/Entertainment",
    "Topic :: Games/Entertainment :: Side-Scrolling/Arcade Games",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]

requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
]

[project.optional-dependencies]
cli = [
	"click>=8.3.1",
]

[project.scripts]
lihzahrd = "lihzahrd.cli.__main__:main"

[dependency-groups]
docs = [
	"furo>=2025.12.19",
	"Sphinx>=8.2.3",
	"sphinx-autobuild>=2025.8.25",
	"sphinx-rtd-theme>=3.0.2",
]
generate = [
	"beautifulsoup4>=4.14.3",
	"lxml>=6.0.2",
]
lint = [
    "black>=26.1.0",
]
test = [
	"pytest>=9.0.0",
	"pytest-cov>=7.0.0",
]

[project.urls]
Repository = "https://g.starshard.space/steffo/lihzahrd/"
Issues = "https://g.starshard.space/steffo/lihzahrd/issues"
Documentation = "https://artifacts.steffo.eu/steffo/lihzahrd/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
default-groups = ["docs", "test", "lint"]

[tool.pytest]
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s | %(name)56s | %(levelname)8s | %(message)s"

[tool.black]
line-length = 120
