# language=rst
"""
Module for :term:`ClassMember` of :class:`~lihzahrd.terraria.data.classenums.npc_enum.NPCEnum`.

.. note::

    This module was partially generated by :class:`lihzahrd._generate.terraria.tiles_generator.TilesGenerator`.

.. note::

    For brevity, only a single :term:`ClassMember` is documented, as an example.

"""

from lihzahrd.terraria.data.classmembers.npc_base import NPCBase
from lihzahrd.terraria.data.classenums.npc_enum import NPCEnum


class Merchant(NPCBase, metaclass=NPCEnum, ID=17, JOB="Merchant"):
    """
    The `Merchant`_.

    .. _Merchant: https://terraria.wiki.gg/wiki/Merchant
    """


class Nurse(NPCBase, metaclass=NPCEnum, ID=18, JOB="Nurse"):
    pass


class ArmsDealer(NPCBase, metaclass=NPCEnum, ID=19, JOB="Arms Dealer"):
    pass


class Dryad(NPCBase, metaclass=NPCEnum, ID=20, JOB="Dryad"):
    pass


class Guide(NPCBase, metaclass=NPCEnum, ID=22, JOB="Guide"):
    pass


class OldMan(NPCBase, metaclass=NPCEnum, ID=37, JOB="Old Man"):
    pass


class Demolitionist(NPCBase, metaclass=NPCEnum, ID=38, JOB="Demolitionist"):
    pass


class Clothier(NPCBase, metaclass=NPCEnum, ID=54, JOB="Clothier"):
    pass


class GoblinTinkerer(NPCBase, metaclass=NPCEnum, ID=107, JOB="Goblin Tinkerer"):
    pass


class Wizard(NPCBase, metaclass=NPCEnum, ID=108, JOB="Wizard"):
    pass


class Mechanic(NPCBase, metaclass=NPCEnum, ID=124, JOB="Mechanic"):
    pass


class SantaClaus(NPCBase, metaclass=NPCEnum, ID=142, JOB="Santa Claus"):
    pass


class Truffle(NPCBase, metaclass=NPCEnum, ID=160, JOB="Truffle"):
    pass


class Steampunker(NPCBase, metaclass=NPCEnum, ID=178, JOB="Steampunker"):
    pass


class DyeTrader(NPCBase, metaclass=NPCEnum, ID=207, JOB="Dye Trader"):
    pass


class PartyGirl(NPCBase, metaclass=NPCEnum, ID=208, JOB="Party Girl"):
    pass


class Cyborg(NPCBase, metaclass=NPCEnum, ID=209, JOB="Cyborg"):
    pass


class Painter(NPCBase, metaclass=NPCEnum, ID=227, JOB="Painter"):
    pass


class WitchDoctor(NPCBase, metaclass=NPCEnum, ID=228, JOB="Witch Doctor"):
    pass


class Pirate(NPCBase, metaclass=NPCEnum, ID=229, JOB="Pirate"):
    pass


class Stylist(NPCBase, metaclass=NPCEnum, ID=353, JOB="Stylist"):
    pass


class Angler(NPCBase, metaclass=NPCEnum, ID=369, JOB="Angler"):
    pass


class TaxCollector(NPCBase, metaclass=NPCEnum, ID=441, JOB="Tax Collector"):
    pass


class Tavernkeep(NPCBase, metaclass=NPCEnum, ID=550, JOB="Tavernkeep"):
    pass


class Golfer(NPCBase, metaclass=NPCEnum, ID=588, JOB="Golfer"):
    pass


class Zoologist(NPCBase, metaclass=NPCEnum, ID=633, JOB="Zoologist"):
    pass


class TownCat(NPCBase, metaclass=NPCEnum, ID=637, JOB="Town Cat"):
    pass


class TownDog(NPCBase, metaclass=NPCEnum, ID=638, JOB="Town Dog"):
    pass


class TownBunny(NPCBase, metaclass=NPCEnum, ID=656, JOB="Town Bunny"):
    pass


class Princess(NPCBase, metaclass=NPCEnum, ID=663, JOB="Princess"):
    pass


__all__ = (
    "Merchant",
    "Nurse",
    "ArmsDealer",
    "Dryad",
    "Guide",
    "OldMan",
    "Demolitionist",
    "Clothier",
    "GoblinTinkerer",
    "Wizard",
    "Mechanic",
    "SantaClaus",
    "Truffle",
    "Steampunker",
    "DyeTrader",
    "PartyGirl",
    "Cyborg",
    "Painter",
    "WitchDoctor",
    "Pirate",
    "Stylist",
    "Angler",
    "TaxCollector",
    "Tavernkeep",
    "Golfer",
    "Zoologist",
    "TownCat",
    "TownDog",
    "TownBunny",
    "Princess",
)
