# language=rst
"""
Module for :term:`ClassMember` of :class:`~lihzahrd.terraria.data.classenums.prefix_enum.PrefixEnum`.

.. note::

    This module was partially generated by :class:`lihzahrd._generate.terraria.tiles_generator.TilesGenerator`.

.. note::

    For brevity, only a single :term:`ClassMember` is documented, as an example.

"""

from lihzahrd.terraria.data.classmembers.prefix_base import PrefixBase
from lihzahrd.terraria.data.classenums.prefix_enum import PrefixEnum


class Large(PrefixBase, metaclass=PrefixEnum, ID=1, NAME="Large"):
    """
    The Large `modifier`_.

    It:

    - increases the size of the affected weapon by 12%
    - increases the tier of the affected item by 1
    - increases the value of the affected item by 25.44%

    .. _modifier: https://terraria.wiki.gg/wiki/Modifiers
    """


class Massive(PrefixBase, metaclass=PrefixEnum, ID=2, NAME="Massive"):
    pass


class Dangerous(PrefixBase, metaclass=PrefixEnum, ID=3, NAME="Dangerous"):
    pass


class Savage(PrefixBase, metaclass=PrefixEnum, ID=4, NAME="Savage"):
    pass


class Sharp(PrefixBase, metaclass=PrefixEnum, ID=5, NAME="Sharp"):
    pass


class Pointy(PrefixBase, metaclass=PrefixEnum, ID=6, NAME="Pointy"):
    pass


class Tiny(PrefixBase, metaclass=PrefixEnum, ID=7, NAME="Tiny"):
    pass


class Terrible(PrefixBase, metaclass=PrefixEnum, ID=8, NAME="Terrible"):
    pass


class Small(PrefixBase, metaclass=PrefixEnum, ID=9, NAME="Small"):
    pass


class Dull(PrefixBase, metaclass=PrefixEnum, ID=10, NAME="Dull"):
    pass


class Unhappy(PrefixBase, metaclass=PrefixEnum, ID=11, NAME="Unhappy"):
    pass


class Bulky(PrefixBase, metaclass=PrefixEnum, ID=12, NAME="Bulky"):
    pass


class Shameful(PrefixBase, metaclass=PrefixEnum, ID=13, NAME="Shameful"):
    pass


class Heavy(PrefixBase, metaclass=PrefixEnum, ID=14, NAME="Heavy"):
    pass


class Light(PrefixBase, metaclass=PrefixEnum, ID=15, NAME="Light"):
    pass


class Sighted(PrefixBase, metaclass=PrefixEnum, ID=16, NAME="Sighted"):
    pass


class Rapid(PrefixBase, metaclass=PrefixEnum, ID=17, NAME="Rapid"):
    pass


class HastyRanged(PrefixBase, metaclass=PrefixEnum, ID=18, NAME="Hasty"):
    pass


class Intimidating(PrefixBase, metaclass=PrefixEnum, ID=19, NAME="Intimidating"):
    pass


class DeadlyRanged(PrefixBase, metaclass=PrefixEnum, ID=20, NAME="Deadly"):
    pass


class Staunch(PrefixBase, metaclass=PrefixEnum, ID=21, NAME="Staunch"):
    pass


class Awful(PrefixBase, metaclass=PrefixEnum, ID=22, NAME="Awful"):
    pass


class Lethargic(PrefixBase, metaclass=PrefixEnum, ID=23, NAME="Lethargic"):
    pass


class Awkward(PrefixBase, metaclass=PrefixEnum, ID=24, NAME="Awkward"):
    pass


class Powerful(PrefixBase, metaclass=PrefixEnum, ID=25, NAME="Powerful"):
    pass


class Mystic(PrefixBase, metaclass=PrefixEnum, ID=26, NAME="Mystic"):
    pass


class Adept(PrefixBase, metaclass=PrefixEnum, ID=27, NAME="Adept"):
    pass


class Masterful(PrefixBase, metaclass=PrefixEnum, ID=28, NAME="Masterful"):
    pass


class Inept(PrefixBase, metaclass=PrefixEnum, ID=29, NAME="Inept"):
    pass


class Ignorant(PrefixBase, metaclass=PrefixEnum, ID=30, NAME="Ignorant"):
    pass


class Deranged(PrefixBase, metaclass=PrefixEnum, ID=31, NAME="Deranged"):
    pass


class Intense(PrefixBase, metaclass=PrefixEnum, ID=32, NAME="Intense"):
    pass


class Taboo(PrefixBase, metaclass=PrefixEnum, ID=33, NAME="Taboo"):
    pass


class Celestial(PrefixBase, metaclass=PrefixEnum, ID=34, NAME="Celestial"):
    pass


class Furious(PrefixBase, metaclass=PrefixEnum, ID=35, NAME="Furious"):
    pass


class Keen(PrefixBase, metaclass=PrefixEnum, ID=36, NAME="Keen"):
    pass


class Superior(PrefixBase, metaclass=PrefixEnum, ID=37, NAME="Superior"):
    pass


class Forceful(PrefixBase, metaclass=PrefixEnum, ID=38, NAME="Forceful"):
    pass


class Broken(PrefixBase, metaclass=PrefixEnum, ID=39, NAME="Broken"):
    pass


class Damaged(PrefixBase, metaclass=PrefixEnum, ID=40, NAME="Damaged"):
    pass


class Shoddy(PrefixBase, metaclass=PrefixEnum, ID=41, NAME="Shoddy"):
    pass


class QuickWeapon(PrefixBase, metaclass=PrefixEnum, ID=42, NAME="Quick"):
    pass


class DeadlyWeapon(PrefixBase, metaclass=PrefixEnum, ID=43, NAME="Deadly"):
    pass


class Agile(PrefixBase, metaclass=PrefixEnum, ID=44, NAME="Agile"):
    pass


class Nimble(PrefixBase, metaclass=PrefixEnum, ID=45, NAME="Nimble"):
    pass


class Murderous(PrefixBase, metaclass=PrefixEnum, ID=46, NAME="Murderous"):
    pass


class Slow(PrefixBase, metaclass=PrefixEnum, ID=47, NAME="Slow"):
    pass


class Sluggish(PrefixBase, metaclass=PrefixEnum, ID=48, NAME="Sluggish"):
    pass


class Lazy(PrefixBase, metaclass=PrefixEnum, ID=49, NAME="Lazy"):
    pass


class Annoying(PrefixBase, metaclass=PrefixEnum, ID=50, NAME="Annoying"):
    pass


class Nasty(PrefixBase, metaclass=PrefixEnum, ID=51, NAME="Nasty"):
    pass


class Manic(PrefixBase, metaclass=PrefixEnum, ID=52, NAME="Manic"):
    pass


class Hurtful(PrefixBase, metaclass=PrefixEnum, ID=53, NAME="Hurtful"):
    pass


class Strong(PrefixBase, metaclass=PrefixEnum, ID=54, NAME="Strong"):
    pass


class Unpleasant(PrefixBase, metaclass=PrefixEnum, ID=55, NAME="Unpleasant"):
    pass


class Weak(PrefixBase, metaclass=PrefixEnum, ID=56, NAME="Weak"):
    pass


class Ruthless(PrefixBase, metaclass=PrefixEnum, ID=57, NAME="Ruthless"):
    pass


class Frenzying(PrefixBase, metaclass=PrefixEnum, ID=58, NAME="Frenzying"):
    pass


class Godly(PrefixBase, metaclass=PrefixEnum, ID=59, NAME="Godly"):
    pass


class Demonic(PrefixBase, metaclass=PrefixEnum, ID=60, NAME="Demonic"):
    pass


class Zealous(PrefixBase, metaclass=PrefixEnum, ID=61, NAME="Zealous"):
    pass


class Hard(PrefixBase, metaclass=PrefixEnum, ID=62, NAME="Hard"):
    pass


class Guarding(PrefixBase, metaclass=PrefixEnum, ID=63, NAME="Guarding"):
    pass


class Armored(PrefixBase, metaclass=PrefixEnum, ID=64, NAME="Armored"):
    pass


class Warding(PrefixBase, metaclass=PrefixEnum, ID=65, NAME="Warding"):
    pass


class Arcane(PrefixBase, metaclass=PrefixEnum, ID=66, NAME="Arcane"):
    pass


class Precise(PrefixBase, metaclass=PrefixEnum, ID=67, NAME="Precise"):
    pass


class Lucky(PrefixBase, metaclass=PrefixEnum, ID=68, NAME="Lucky"):
    pass


class Jagged(PrefixBase, metaclass=PrefixEnum, ID=69, NAME="Jagged"):
    pass


class Spiked(PrefixBase, metaclass=PrefixEnum, ID=70, NAME="Spiked"):
    pass


class Angry(PrefixBase, metaclass=PrefixEnum, ID=71, NAME="Angry"):
    pass


class Menacing(PrefixBase, metaclass=PrefixEnum, ID=72, NAME="Menacing"):
    pass


class Brisk(PrefixBase, metaclass=PrefixEnum, ID=73, NAME="Brisk"):
    pass


class Fleeting(PrefixBase, metaclass=PrefixEnum, ID=74, NAME="Fleeting"):
    pass


class HastyAccessory(PrefixBase, metaclass=PrefixEnum, ID=75, NAME="Hasty"):
    pass


class QuickAccessory(PrefixBase, metaclass=PrefixEnum, ID=76, NAME="Quick"):
    pass


class Wild(PrefixBase, metaclass=PrefixEnum, ID=77, NAME="Wild"):
    pass


class Rash(PrefixBase, metaclass=PrefixEnum, ID=78, NAME="Rash"):
    pass


class Intrepid(PrefixBase, metaclass=PrefixEnum, ID=79, NAME="Intrepid"):
    pass


class Violent(PrefixBase, metaclass=PrefixEnum, ID=80, NAME="Violent"):
    pass


class Legendary(PrefixBase, metaclass=PrefixEnum, ID=81, NAME="Legendary"):
    pass


class Unreal(PrefixBase, metaclass=PrefixEnum, ID=82, NAME="Unreal"):
    pass


class Mythical(PrefixBase, metaclass=PrefixEnum, ID=83, NAME="Mythical"):
    pass


class LegendaryTerrarian(PrefixBase, metaclass=PrefixEnum, ID=84, NAME="Legendary 2"):
    pass


class Fabled(PrefixBase, metaclass=PrefixEnum, ID=85, NAME="Fabled"):
    pass


class Loyal(PrefixBase, metaclass=PrefixEnum, ID=86, NAME="Loyal"):
    pass


class Worthy(PrefixBase, metaclass=PrefixEnum, ID=87, NAME="Worthy"):
    pass


class Focused(PrefixBase, metaclass=PrefixEnum, ID=88, NAME="Focused"):
    pass


class Patient(PrefixBase, metaclass=PrefixEnum, ID=89, NAME="Patient"):
    pass


class Rabid(PrefixBase, metaclass=PrefixEnum, ID=90, NAME="Rabid"):
    pass


class IllTempered(PrefixBase, metaclass=PrefixEnum, ID=91, NAME="Ill-Tempered"):
    pass


class Petty(PrefixBase, metaclass=PrefixEnum, ID=92, NAME="Petty"):
    pass


class Feeble(PrefixBase, metaclass=PrefixEnum, ID=93, NAME="Feeble"):
    pass


class Skittish(PrefixBase, metaclass=PrefixEnum, ID=94, NAME="Skittish"):
    pass


class Eager(PrefixBase, metaclass=PrefixEnum, ID=95, NAME="Eager"):
    pass


class Ballistic(PrefixBase, metaclass=PrefixEnum, ID=96, NAME="Ballistic"):
    pass


class Scraggling(PrefixBase, metaclass=PrefixEnum, ID=97, NAME="Scraggling"):
    pass


__all__ = (
    "Large",
    "Massive",
    "Dangerous",
    "Savage",
    "Sharp",
    "Pointy",
    "Tiny",
    "Terrible",
    "Small",
    "Dull",
    "Unhappy",
    "Bulky",
    "Shameful",
    "Heavy",
    "Light",
    "Sighted",
    "Rapid",
    "HastyRanged",
    "Intimidating",
    "DeadlyRanged",
    "Staunch",
    "Awful",
    "Lethargic",
    "Awkward",
    "Powerful",
    "Mystic",
    "Adept",
    "Masterful",
    "Inept",
    "Ignorant",
    "Deranged",
    "Intense",
    "Taboo",
    "Celestial",
    "Furious",
    "Keen",
    "Superior",
    "Forceful",
    "Broken",
    "Damaged",
    "Shoddy",
    "QuickWeapon",
    "DeadlyWeapon",
    "Agile",
    "Nimble",
    "Murderous",
    "Slow",
    "Sluggish",
    "Lazy",
    "Annoying",
    "Nasty",
    "Manic",
    "Hurtful",
    "Strong",
    "Unpleasant",
    "Weak",
    "Ruthless",
    "Frenzying",
    "Godly",
    "Demonic",
    "Zealous",
    "Hard",
    "Guarding",
    "Armored",
    "Warding",
    "Arcane",
    "Precise",
    "Lucky",
    "Jagged",
    "Spiked",
    "Angry",
    "Menacing",
    "Brisk",
    "Fleeting",
    "HastyAccessory",
    "QuickAccessory",
    "Wild",
    "Rash",
    "Intrepid",
    "Violent",
    "Legendary",
    "Unreal",
    "Mythical",
    "LegendaryTerrarian",
    "Fabled",
    "Loyal",
    "Worthy",
    "Focused",
    "Patient",
    "Rabid",
    "IllTempered",
    "Petty",
    "Feeble",
    "Skittish",
    "Eager",
    "Ballistic",
    "Scraggling",
)
