# language=rst
"""
Module for :term:`ClassMember` of :class:`~lihzahrd.terraria.data.classenums.wall_enum.WallEnum`.

.. note::

    This module was partially generated by :class:`lihzahrd._generate.terraria.tiles_generator.TilesGenerator`.

.. note::

    For brevity, only a single :term:`ClassMember` is documented, as an example.

"""

from lihzahrd.terraria.data.classmembers.wall_base import WallBase
from lihzahrd.terraria.data.classenums.wall_enum import WallEnum
from lihzahrd.terraria.utils.structures.color import ColorRGB


class StoneWall(WallBase, metaclass=WallEnum, ID=1, NAME="Stone Wall"):
    """
    A `Stone Wall`_.

    .. _Stone Wall: https://terraria.wiki.gg/wiki/Stone_Wall
    """

    COLOR = ColorRGB(h="#343434")


class DirtWall(WallBase, metaclass=WallEnum, ID=2, NAME="Dirt Wall"):
    COLOR = ColorRGB(h="#583D2E")


class StoneWallWall(WallBase, metaclass=WallEnum, ID=3, NAME="Stone Wall"):
    COLOR = ColorRGB(h="#3D3A4E")


class WoodWall(WallBase, metaclass=WallEnum, ID=4, NAME="Wood Wall"):
    COLOR = ColorRGB(h="#523C2D")


class GrayBrickWall(WallBase, metaclass=WallEnum, ID=5, NAME="Gray Brick Wall"):
    COLOR = ColorRGB(h="#3C3C3C")


class RedBrickWall(WallBase, metaclass=WallEnum, ID=6, NAME="Red Brick Wall"):
    COLOR = ColorRGB(h="#5B1E1E")


class BlueBrickWall(WallBase, metaclass=WallEnum, ID=7, NAME="Blue Brick Wall"):
    COLOR = ColorRGB(h="#3D4456")


class GreenBrickWall(WallBase, metaclass=WallEnum, ID=8, NAME="Green Brick Wall"):
    COLOR = ColorRGB(h="#384147")


class PinkBrickWall(WallBase, metaclass=WallEnum, ID=9, NAME="Pink Brick Wall"):
    COLOR = ColorRGB(h="#603E5C")


class GoldBrickWall(WallBase, metaclass=WallEnum, ID=10, NAME="Gold Brick Wall"):
    COLOR = ColorRGB(h="#64510A")


class SilverBrickWall(WallBase, metaclass=WallEnum, ID=11, NAME="Silver Brick Wall"):
    COLOR = ColorRGB(h="#616969")


class CopperBrickWall(WallBase, metaclass=WallEnum, ID=12, NAME="Copper Brick Wall"):
    COLOR = ColorRGB(h="#532E16")


class HellstoneBrickWall(WallBase, metaclass=WallEnum, ID=13, NAME="Hellstone Brick Wall"):
    COLOR = ColorRGB(h="#492929")


class ObsidianWall(WallBase, metaclass=WallEnum, ID=14, NAME="Obsidian Wall"):
    COLOR = ColorRGB(h="#020202")


class MudWall(WallBase, metaclass=WallEnum, ID=15, NAME="Mud Wall"):
    COLOR = ColorRGB(h="#31282B")


class DirtWallWall(WallBase, metaclass=WallEnum, ID=16, NAME="Dirt Wall"):
    COLOR = ColorRGB(h="#583D2E")
    BLEND = 2


class BlueBrickWallWall(WallBase, metaclass=WallEnum, ID=17, NAME="Blue Brick Wall"):
    COLOR = ColorRGB(h="#492929")
    BLEND = 7


class GreenBrickWallWall(WallBase, metaclass=WallEnum, ID=18, NAME="Green Brick Wall"):
    COLOR = ColorRGB(h="#384147")
    BLEND = 8


class PinkBrickWallWall(WallBase, metaclass=WallEnum, ID=19, NAME="Pink Brick Wall"):
    COLOR = ColorRGB(h="#603E5C")
    BLEND = 9


class ObsidianBrickWall(WallBase, metaclass=WallEnum, ID=20, NAME="Obsidian Brick Wall"):
    COLOR = ColorRGB(h="#0F0F0F")
    BLEND = 14


class GlassWall(WallBase, metaclass=WallEnum, ID=21, NAME="Glass Wall"):
    COLOR = ColorRGB(h="#12242C")


class PearlstoneBrickWall(WallBase, metaclass=WallEnum, ID=22, NAME="Pearlstone Brick Wall"):
    COLOR = ColorRGB(h="#827C79")


class IridescentBrickWall(WallBase, metaclass=WallEnum, ID=23, NAME="Iridescent Brick Wall"):
    COLOR = ColorRGB(h="#56494B")


class MudstoneBrickWall(WallBase, metaclass=WallEnum, ID=24, NAME="Mudstone Brick Wall"):
    COLOR = ColorRGB(h="#403033")


class CobaltBrickWall(WallBase, metaclass=WallEnum, ID=25, NAME="Cobalt Brick Wall"):
    COLOR = ColorRGB(h="#0B233E")


class MythrilBrickWall(WallBase, metaclass=WallEnum, ID=26, NAME="Mythril Brick Wall"):
    COLOR = ColorRGB(h="#3C5B3A")


class PlankedWall(WallBase, metaclass=WallEnum, ID=27, NAME="Planked Wall"):
    COLOR = ColorRGB(h="#3A291D")


class PearlstoneWall(WallBase, metaclass=WallEnum, ID=28, NAME="Pearlstone Wall"):
    COLOR = ColorRGB(h="#515465")


class CandyCaneWall(WallBase, metaclass=WallEnum, ID=29, NAME="Candy Cane Wall"):
    COLOR = ColorRGB(h="#581717")


class GreenCandyCaneWall(WallBase, metaclass=WallEnum, ID=30, NAME="Green Candy Cane Wall"):
    COLOR = ColorRGB(h="#2C6A26")


class SnowBrickWall(WallBase, metaclass=WallEnum, ID=31, NAME="Snow Brick Wall"):
    COLOR = ColorRGB(h="#6B7577")


class AdamantiteBeamWall(WallBase, metaclass=WallEnum, ID=32, NAME="Adamantite Beam Wall"):
    COLOR = ColorRGB(h="#5a122b")


class DemoniteBrickWall(WallBase, metaclass=WallEnum, ID=33, NAME="Demonite Brick Wall"):
    COLOR = ColorRGB(h="#46455e")


class SandstoneBrickWall(WallBase, metaclass=WallEnum, ID=34, NAME="Sandstone Brick Wall"):
    COLOR = ColorRGB(h="#6c6748")


class EbonstoneBrickWall(WallBase, metaclass=WallEnum, ID=35, NAME="Ebonstone Brick Wall"):
    COLOR = ColorRGB(h="#333346")


class RedStuccoWall(WallBase, metaclass=WallEnum, ID=36, NAME="Red Stucco Wall"):
    COLOR = ColorRGB(h="#704b46")


class YellowStuccoWall(WallBase, metaclass=WallEnum, ID=37, NAME="Yellow Stucco Wall"):
    COLOR = ColorRGB(h="#574f30")


class GreenStuccoWall(WallBase, metaclass=WallEnum, ID=38, NAME="Green Stucco Wall"):
    COLOR = ColorRGB(h="#5a5d73")


class GrayStuccoWall(WallBase, metaclass=WallEnum, ID=39, NAME="Gray Stucco Wall"):
    COLOR = ColorRGB(h="#6d6d6b")


class SnowWall(WallBase, metaclass=WallEnum, ID=40, NAME="Snow Wall"):
    COLOR = ColorRGB(h="#577173")


class EbonwoodWall(WallBase, metaclass=WallEnum, ID=41, NAME="Ebonwood Wall"):
    COLOR = ColorRGB(h="#3a3944")


class RichMahoganyWall(WallBase, metaclass=WallEnum, ID=42, NAME="Rich Mahogany Wall"):
    COLOR = ColorRGB(h="#4e1e20")


class PearlwoodWall(WallBase, metaclass=WallEnum, ID=43, NAME="Pearlwood Wall"):
    COLOR = ColorRGB(h="#776c51")


class RainbowBrickWall(WallBase, metaclass=WallEnum, ID=44, NAME="Rainbow Brick Wall"):
    COLOR = ColorRGB(h="#414141")


class TinBrickWall(WallBase, metaclass=WallEnum, ID=45, NAME="Tin Brick Wall"):
    COLOR = ColorRGB(h="#3c3b33")


class TungstenBrickWall(WallBase, metaclass=WallEnum, ID=46, NAME="Tungsten Brick Wall"):
    COLOR = ColorRGB(h="#586758")


class PlatinumBrickWall(WallBase, metaclass=WallEnum, ID=47, NAME="Platinum Brick Wall"):
    COLOR = ColorRGB(h="#666b75")


class AmethystWall(WallBase, metaclass=WallEnum, ID=48, NAME="Amethyst Wall"):
    COLOR = ColorRGB(h="#3c2452")
    BLEND = 1


class TopazWall(WallBase, metaclass=WallEnum, ID=49, NAME="Topaz Wall"):
    COLOR = ColorRGB(h="#614b1c")
    BLEND = 1


class SapphireWall(WallBase, metaclass=WallEnum, ID=50, NAME="Sapphire Wall"):
    COLOR = ColorRGB(h="#32527d")
    BLEND = 1


class EmeraldWall(WallBase, metaclass=WallEnum, ID=51, NAME="Emerald Wall"):
    COLOR = ColorRGB(h="#1c4924")
    BLEND = 1


class RubyWall(WallBase, metaclass=WallEnum, ID=52, NAME="Ruby Wall"):
    COLOR = ColorRGB(h="#431d22")
    BLEND = 1


class DiamondWall(WallBase, metaclass=WallEnum, ID=53, NAME="Diamond Wall"):
    COLOR = ColorRGB(h="#234249")
    BLEND = 1


class MossWall(WallBase, metaclass=WallEnum, ID=54, NAME="Moss Wall"):
    COLOR = ColorRGB(h="#304a42")


class GreenMossWall(WallBase, metaclass=WallEnum, ID=55, NAME="Green Moss Wall"):
    COLOR = ColorRGB(h="#4f4f33")


class RedMossWall(WallBase, metaclass=WallEnum, ID=56, NAME="Red Moss Wall"):
    COLOR = ColorRGB(h="#4e3938")


class BlueMossWall(WallBase, metaclass=WallEnum, ID=57, NAME="Blue Moss Wall"):
    COLOR = ColorRGB(h="#334452")


class PurpleMossWall(WallBase, metaclass=WallEnum, ID=58, NAME="Purple Moss Wall"):
    COLOR = ColorRGB(h="#432f49")


class RockyDirtWall(WallBase, metaclass=WallEnum, ID=59, NAME="Rocky Dirt Wall"):
    COLOR = ColorRGB(h="#583d2e")
    BLEND = 2


class LivingLeafWall(WallBase, metaclass=WallEnum, ID=60, NAME="Living Leaf Wall"):
    COLOR = ColorRGB(h="#013e17")


class RockWall(WallBase, metaclass=WallEnum, ID=61, NAME="Rock Wall"):
    COLOR = ColorRGB(h="#362619")


class SpiderCaveWall(WallBase, metaclass=WallEnum, ID=62, NAME="Spider Cave Wall"):
    COLOR = ColorRGB(h="#242424")


class ShrubWall(WallBase, metaclass=WallEnum, ID=63, NAME="Shrub Wall"):
    COLOR = ColorRGB(h="#235f39")


class ShrubWallWall(WallBase, metaclass=WallEnum, ID=64, NAME="Shrub Wall"):
    COLOR = ColorRGB(h="#3f5f23")


class ShrubWall2(WallBase, metaclass=WallEnum, ID=65, NAME="Shrub Wall"):
    COLOR = ColorRGB(h="#1e5030")


class GrassWall(WallBase, metaclass=WallEnum, ID=66, NAME="Grass Wall"):
    COLOR = ColorRGB(h="#1e5030")


class JungleWall(WallBase, metaclass=WallEnum, ID=67, NAME="Jungle Wall"):
    COLOR = ColorRGB(h="#35501e")


class FlowerWall(WallBase, metaclass=WallEnum, ID=68, NAME="Flower Wall"):
    COLOR = ColorRGB(h="#1e5030")


class ShrubWall3(WallBase, metaclass=WallEnum, ID=69, NAME="Shrub Wall"):
    COLOR = ColorRGB(h="#333250")


class ShrubWall4(WallBase, metaclass=WallEnum, ID=70, NAME="Shrub Wall"):
    COLOR = ColorRGB(h="#143736")


class IceWall(WallBase, metaclass=WallEnum, ID=71, NAME="Ice Wall"):
    COLOR = ColorRGB(h="#306085")


class CactusWall(WallBase, metaclass=WallEnum, ID=72, NAME="Cactus Wall"):
    COLOR = ColorRGB(h="#34540c")


class CloudWall(WallBase, metaclass=WallEnum, ID=73, NAME="Cloud Wall"):
    COLOR = ColorRGB(h="#e4ecee")


class MushroomWall(WallBase, metaclass=WallEnum, ID=74, NAME="Mushroom Wall"):
    COLOR = ColorRGB(h="#313b8c")


class BoneBlockWall(WallBase, metaclass=WallEnum, ID=75, NAME="Bone Block Wall"):
    COLOR = ColorRGB(h="#63633c")


class SlimeBlockWall(WallBase, metaclass=WallEnum, ID=76, NAME="Slime Block Wall"):
    COLOR = ColorRGB(h="#213c79")


class FleshBlockWall(WallBase, metaclass=WallEnum, ID=77, NAME="Flesh Block Wall"):
    COLOR = ColorRGB(h="#3d0d10")


class LivingWoodWall(WallBase, metaclass=WallEnum, ID=78, NAME="Living Wood Wall"):
    COLOR = ColorRGB(h="#513426")


class CaveWall(WallBase, metaclass=WallEnum, ID=79, NAME="Cave Wall"):
    COLOR = ColorRGB(h="#332f60")


class MushroomWallWall(WallBase, metaclass=WallEnum, ID=80, NAME="Mushroom Wall"):
    COLOR = ColorRGB(h="#313b8c")


class ClayWall(WallBase, metaclass=WallEnum, ID=81, NAME="Clay Wall"):
    COLOR = ColorRGB(h="#844545")


class DiscWall(WallBase, metaclass=WallEnum, ID=82, NAME="Disc Wall"):
    COLOR = ColorRGB(h="#4d4022")


class HellstoneWall(WallBase, metaclass=WallEnum, ID=83, NAME="Hellstone Wall"):
    COLOR = ColorRGB(h="#3f1c21")


class IceBrickWall(WallBase, metaclass=WallEnum, ID=84, NAME="Ice Brick Wall"):
    COLOR = ColorRGB(h="#596f72")


class ShadewoodWall(WallBase, metaclass=WallEnum, ID=85, NAME="Shadewood Wall"):
    COLOR = ColorRGB(h="#2a363f")


class HiveWall(WallBase, metaclass=WallEnum, ID=86, NAME="Hive Wall"):
    COLOR = ColorRGB(h="#8c5131")


class LihzahrdBrickWall(WallBase, metaclass=WallEnum, ID=87, NAME="Lihzahrd Brick Wall"):
    COLOR = ColorRGB(h="#320f08")


class PurpleStainedGlass(WallBase, metaclass=WallEnum, ID=88, NAME="Purple Stained Glass"):
    COLOR = ColorRGB(h="#6c3c82")


class YellowStainedGlass(WallBase, metaclass=WallEnum, ID=89, NAME="Yellow Stained Glass"):
    COLOR = ColorRGB(h="#787a45")


class BlueStainedGlass(WallBase, metaclass=WallEnum, ID=90, NAME="Blue Stained Glass"):
    COLOR = ColorRGB(h="#35498a")


class GreenStainedGlass(WallBase, metaclass=WallEnum, ID=91, NAME="Green Stained Glass"):
    COLOR = ColorRGB(h="#45794f")


class RedStainedGlass(WallBase, metaclass=WallEnum, ID=92, NAME="Red Stained Glass"):
    COLOR = ColorRGB(h="#8a3535")


class MulticoloredStainedGlass(WallBase, metaclass=WallEnum, ID=93, NAME="Multicolored Stained Glass"):
    COLOR = ColorRGB(h="#99255c")


class SmallBlueBrickWall(WallBase, metaclass=WallEnum, ID=94, NAME="Small Blue Brick Wall"):
    COLOR = ColorRGB(h="#303f46")


class BlueBlockWall(WallBase, metaclass=WallEnum, ID=95, NAME="Blue Block Wall"):
    COLOR = ColorRGB(h="#393643")


class PinkBlockWall(WallBase, metaclass=WallEnum, ID=96, NAME="Pink Block Wall"):
    COLOR = ColorRGB(h="#593e5f")


class SmallPinkBrickWall(WallBase, metaclass=WallEnum, ID=97, NAME="Small Pink Brick Wall"):
    COLOR = ColorRGB(h="#4e3245")


class SmallGreenBrickWall(WallBase, metaclass=WallEnum, ID=98, NAME="Small Green Brick Wall"):
    COLOR = ColorRGB(h="#384745")


class GreenBlockWall(WallBase, metaclass=WallEnum, ID=99, NAME="Green Block Wall"):
    COLOR = ColorRGB(h="#383e47")


class BlueSlabWall(WallBase, metaclass=WallEnum, ID=100, NAME="Blue Slab Wall"):
    COLOR = ColorRGB(h="#303f46")


class BlueTiledWall(WallBase, metaclass=WallEnum, ID=101, NAME="Blue Tiled Wall"):
    COLOR = ColorRGB(h="#393643")


class PinkSlabWall(WallBase, metaclass=WallEnum, ID=102, NAME="Pink Slab Wall"):
    COLOR = ColorRGB(h="#48324d")


class PinkTiledWall(WallBase, metaclass=WallEnum, ID=103, NAME="Pink Tiled Wall"):
    COLOR = ColorRGB(h="#4e3245")


class GreenSlabWall(WallBase, metaclass=WallEnum, ID=104, NAME="Green Slab Wall"):
    COLOR = ColorRGB(h="#445747")


class GreenTiledWall(WallBase, metaclass=WallEnum, ID=105, NAME="Green Tiled Wall"):
    COLOR = ColorRGB(h="#383e47")


class WoodenFence(WallBase, metaclass=WallEnum, ID=106, NAME="Wooden Fence"):
    COLOR = ColorRGB(h="#604438")


class LeadFence(WallBase, metaclass=WallEnum, ID=107, NAME="Lead Fence"):
    COLOR = ColorRGB(h="#3c3c3c")


class HiveWallWall(WallBase, metaclass=WallEnum, ID=108, NAME="Hive Wall"):
    COLOR = ColorRGB(h="#8c5131")


class PalladiumColumnWall(WallBase, metaclass=WallEnum, ID=109, NAME="Palladium Column Wall"):
    COLOR = ColorRGB(h="#5e1911")


class BubblegumBlockWall(WallBase, metaclass=WallEnum, ID=110, NAME="Bubblegum Block Wall"):
    COLOR = ColorRGB(h="#994996")


class TitanstoneBlockWall(WallBase, metaclass=WallEnum, ID=111, NAME="Titanstone Block Wall"):
    COLOR = ColorRGB(h="#1f1814")


class LihzahrdBrickWallWall(WallBase, metaclass=WallEnum, ID=112, NAME="Lihzahrd Brick Wall"):
    COLOR = ColorRGB(h="#320F08")


class PumpkinWall(WallBase, metaclass=WallEnum, ID=113, NAME="Pumpkin Wall"):
    COLOR = ColorRGB(h="#803700")


class HayWall(WallBase, metaclass=WallEnum, ID=114, NAME="Hay Wall"):
    COLOR = ColorRGB(h="#745E19")


class SpookyWoodWall(WallBase, metaclass=WallEnum, ID=115, NAME="Spooky Wood Wall"):
    COLOR = ColorRGB(h="#33243F")


class ChristmasTreeWallpaper(WallBase, metaclass=WallEnum, ID=116, NAME="Christmas Tree Wallpaper"):
    COLOR = ColorRGB(h="#5A1B1C")


class OrnamentWallpaper(WallBase, metaclass=WallEnum, ID=117, NAME="Ornament Wallpaper"):
    COLOR = ColorRGB(h="#7D7A71")


class CandyCaneWallpaper(WallBase, metaclass=WallEnum, ID=118, NAME="Candy Cane Wallpaper"):
    COLOR = ColorRGB(h="#073112")


class FestiveWallpaper(WallBase, metaclass=WallEnum, ID=119, NAME="Festive Wallpaper"):
    COLOR = ColorRGB(h="#69181B")


class StarsWallpaper(WallBase, metaclass=WallEnum, ID=120, NAME="Stars Wallpaper"):
    COLOR = ColorRGB(h="#111F41")


class SquigglesWallpaper(WallBase, metaclass=WallEnum, ID=121, NAME="Squiggles Wallpaper"):
    COLOR = ColorRGB(h="#C6C3B7")


class SnowflakeWallpaper(WallBase, metaclass=WallEnum, ID=122, NAME="Snowflake Wallpaper"):
    COLOR = ColorRGB(h="#6E6E7E")


class KrampusHornWallpaper(WallBase, metaclass=WallEnum, ID=123, NAME="Krampus Horn Wallpaper"):
    COLOR = ColorRGB(h="#85755F")


class BluegreenWallpaper(WallBase, metaclass=WallEnum, ID=124, NAME="Bluegreen Wallpaper"):
    COLOR = ColorRGB(h="#100340")


class GrinchFingerWallpaper(WallBase, metaclass=WallEnum, ID=125, NAME="Grinch Finger Wallpaper"):
    COLOR = ColorRGB(h="#748352")


class FancyGreyWallpaper(WallBase, metaclass=WallEnum, ID=126, NAME="Fancy Grey Wallpaper"):
    COLOR = ColorRGB(h="#8F919D")


class IceFloeWallpaper(WallBase, metaclass=WallEnum, ID=127, NAME="Ice Floe Wallpaper"):
    COLOR = ColorRGB(h="#8CB9E2")


class MusicWallpaper(WallBase, metaclass=WallEnum, ID=128, NAME="Music Wallpaper"):
    COLOR = ColorRGB(h="#6F1975")


class PurpleRainWallpaper(WallBase, metaclass=WallEnum, ID=129, NAME="Purple Rain Wallpaper"):
    COLOR = ColorRGB(h="#311B91")


class RainbowWallpaper(WallBase, metaclass=WallEnum, ID=130, NAME="Rainbow Wallpaper"):
    COLOR = ColorRGB(h="#6505C1")


class SparkleStoneWallpaper(WallBase, metaclass=WallEnum, ID=131, NAME="Sparkle Stone Wallpaper"):
    COLOR = ColorRGB(h="#575E7D")


class StarlitHeavenWallpaper(WallBase, metaclass=WallEnum, ID=132, NAME="Starlit Heaven Wallpaper"):
    COLOR = ColorRGB(h="#060606")


class BubbleWallpaper(WallBase, metaclass=WallEnum, ID=133, NAME="Bubble Wallpaper"):
    COLOR = ColorRGB(h="#4D3FA9")


class CopperPipeWallpaper(WallBase, metaclass=WallEnum, ID=134, NAME="Copper Pipe Wallpaper"):
    COLOR = ColorRGB(h="#C25C17")


class DuckyWallpaper(WallBase, metaclass=WallEnum, ID=135, NAME="Ducky Wallpaper"):
    COLOR = ColorRGB(h="#177FA8")


class WaterfallWall(WallBase, metaclass=WallEnum, ID=136, NAME="Waterfall Wall"):
    COLOR = ColorRGB(h="#285697")


class LavafallWall(WallBase, metaclass=WallEnum, ID=137, NAME="Lavafall Wall"):
    COLOR = ColorRGB(h="#B7210F")


class EbonwoodFence(WallBase, metaclass=WallEnum, ID=138, NAME="Ebonwood Fence"):
    COLOR = ColorRGB(h="#9989A5")


class RichMahoganyFence(WallBase, metaclass=WallEnum, ID=139, NAME="Rich Mahogany Fence"):
    COLOR = ColorRGB(h="#A36368")


class PearlwoodFence(WallBase, metaclass=WallEnum, ID=140, NAME="Pearlwood Fence"):
    COLOR = ColorRGB(h="#776C51")


class ShadewoodFence(WallBase, metaclass=WallEnum, ID=141, NAME="Shadewood Fence"):
    COLOR = ColorRGB(h="#586976")


class WhiteDynastyWall(WallBase, metaclass=WallEnum, ID=142, NAME="White Dynasty Wall"):
    COLOR = ColorRGB(h="#E0DACC")


class BlueDynastyWall(WallBase, metaclass=WallEnum, ID=143, NAME="Blue Dynasty Wall"):
    COLOR = ColorRGB(h="#516863")


class ArcaneRuneWall(WallBase, metaclass=WallEnum, ID=144, NAME="Arcane Rune Wall"):
    COLOR = ColorRGB(h="#3E1C57")


class IronFence(WallBase, metaclass=WallEnum, ID=145, NAME="Iron Fence"):
    COLOR = ColorRGB(h="#919191")


class CopperPlatingWall(WallBase, metaclass=WallEnum, ID=146, NAME="Copper Plating Wall"):
    COLOR = ColorRGB(h="#703712")


class StoneSlabWall(WallBase, metaclass=WallEnum, ID=147, NAME="Stone Slab Wall"):
    COLOR = ColorRGB(h="#4C4C4C")


class Sail(WallBase, metaclass=WallEnum, ID=148, NAME="Sail"):
    COLOR = ColorRGB(h="#E5DAA1")


class BorealWoodWall(WallBase, metaclass=WallEnum, ID=149, NAME="Boreal Wood Wall"):
    COLOR = ColorRGB(h="#504237")


class BorealwoodFence(WallBase, metaclass=WallEnum, ID=150, NAME="Boreal wood Fence"):
    COLOR = ColorRGB(h="#6B5647")


class PalmWoodWall(WallBase, metaclass=WallEnum, ID=151, NAME="Palm Wood Wall"):
    COLOR = ColorRGB(h="#664B22")


class PalmWoodFence(WallBase, metaclass=WallEnum, ID=152, NAME="Palm Wood Fence"):
    COLOR = ColorRGB(h="#B68D56")


class AmberGemsparkWall(WallBase, metaclass=WallEnum, ID=153, NAME="Amber Gemspark Wall"):
    COLOR = ColorRGB(h="#FF743F")


class AmethystGemsparkWall(WallBase, metaclass=WallEnum, ID=154, NAME="Amethyst Gemspark Wall"):
    COLOR = ColorRGB(h="#BF3FFF")


class DiamondGemsparkWall(WallBase, metaclass=WallEnum, ID=155, NAME="Diamond Gemspark Wall"):
    COLOR = ColorRGB(h="#DBDBE8")


class EmeraldGemsparkWall(WallBase, metaclass=WallEnum, ID=156, NAME="Emerald Gemspark Wall"):
    COLOR = ColorRGB(h="#3FFF47")


class OfflineAmberGemsparkWall(WallBase, metaclass=WallEnum, ID=157, NAME="Offline Amber Gemspark Wall"):
    COLOR = ColorRGB(h="#763F25")


class OfflineAmethystGemsparkWall(WallBase, metaclass=WallEnum, ID=158, NAME="Offline Amethyst Gemspark Wall"):
    COLOR = ColorRGB(h="#512576")


class OfflineDiamondGemsparkWall(WallBase, metaclass=WallEnum, ID=159, NAME="Offline Diamond Gemspark Wall"):
    COLOR = ColorRGB(h="#404359")


class OfflineEmeraldGemsparkWall(WallBase, metaclass=WallEnum, ID=160, NAME="Offline Emerald Gemspark Wall"):
    COLOR = ColorRGB(h="#257634")


class OfflineRubyGemsparkWall(WallBase, metaclass=WallEnum, ID=161, NAME="Offline Ruby Gemspark Wall"):
    COLOR = ColorRGB(h="#76253A")


class OfflineSapphireGemsparkWall(WallBase, metaclass=WallEnum, ID=162, NAME="Offline Sapphire Gemspark Wall"):
    COLOR = ColorRGB(h="#252576")


class OfflineTopazGemsparkWall(WallBase, metaclass=WallEnum, ID=163, NAME="Offline Topaz Gemspark Wall"):
    COLOR = ColorRGB(h="#767125")


class RubyGemsparkWall(WallBase, metaclass=WallEnum, ID=164, NAME="Ruby Gemspark Wall"):
    COLOR = ColorRGB(h="#FF3F3F")


class SapphireGemsparkWall(WallBase, metaclass=WallEnum, ID=165, NAME="Sapphire Gemspark Wall"):
    COLOR = ColorRGB(h="#3F51FF")


class TopazGemsparkWall(WallBase, metaclass=WallEnum, ID=166, NAME="Topaz Gemspark Wall"):
    COLOR = ColorRGB(h="#EFFF3F")


class TinPlatingWall(WallBase, metaclass=WallEnum, ID=167, NAME="Tin Plating Wall"):
    COLOR = ColorRGB(h="#464433")


class ConfettiWall(WallBase, metaclass=WallEnum, ID=168, NAME="Confetti Wall"):
    COLOR = ColorRGB(h="#0C6A8A")


class MidnightConfettiWall(WallBase, metaclass=WallEnum, ID=169, NAME="Midnight Confetti Wall"):
    COLOR = ColorRGB(h="#850C77")


class Wall170(WallBase, metaclass=WallEnum, ID=170, NAME="Wall 170"):
    COLOR = ColorRGB(h="#3B2716")


class Wall171(WallBase, metaclass=WallEnum, ID=171, NAME="Wall 171"):
    COLOR = ColorRGB(h="#3B2716")


class HoneyfallWall(WallBase, metaclass=WallEnum, ID=172, NAME="Honeyfall Wall"):
    COLOR = ColorRGB(h="#A36000")


class ChlorophyteBrickWall(WallBase, metaclass=WallEnum, ID=173, NAME="Chlorophyte Brick Wall"):
    COLOR = ColorRGB(h="#082A27")


class CrimtaneBrickWall(WallBase, metaclass=WallEnum, ID=174, NAME="Crimtane Brick Wall"):
    COLOR = ColorRGB(h="#451D26")


class ShroomitePlatingWall(WallBase, metaclass=WallEnum, ID=175, NAME="Shroomite Plating Wall"):
    COLOR = ColorRGB(h="#0F0969")


class MartianConduitWall(WallBase, metaclass=WallEnum, ID=176, NAME="Martian Conduit Wall"):
    COLOR = ColorRGB(h="#2C2934")


class HellstoneBrickWallWall(WallBase, metaclass=WallEnum, ID=177, NAME="Hellstone Brick Wall"):
    COLOR = ColorRGB(h="#5D2B2B")


class MarbleWall(WallBase, metaclass=WallEnum, ID=178, NAME="Marble Wall"):
    COLOR = ColorRGB(h="#868DA0")


class MarbleBlockWall(WallBase, metaclass=WallEnum, ID=179, NAME="Marble Block Wall"):
    COLOR = ColorRGB(h="#9AA2B1")


class GraniteWall(WallBase, metaclass=WallEnum, ID=180, NAME="Granite Wall"):
    COLOR = ColorRGB(h="#0C0A19")


class GraniteBlockWall(WallBase, metaclass=WallEnum, ID=181, NAME="Granite Block Wall"):
    COLOR = ColorRGB(h="#1A1733")


class MeteoriteBrickWall(WallBase, metaclass=WallEnum, ID=182, NAME="Meteorite Brick Wall"):
    COLOR = ColorRGB(h="#4A4781")


class MarbleWallWall(WallBase, metaclass=WallEnum, ID=183, NAME="Marble Wall"):
    COLOR = ColorRGB(h="#9AA2B1")


class GraniteWallWall(WallBase, metaclass=WallEnum, ID=184, NAME="Granite Wall"):
    COLOR = ColorRGB(h="#141D49")


class Wall185(WallBase, metaclass=WallEnum, ID=185, NAME="Wall 185"):
    COLOR = ColorRGB(h="#525252")


class CrystalWall(WallBase, metaclass=WallEnum, ID=186, NAME="Crystal Wall"):
    COLOR = ColorRGB(h="#260942")


class SandstoneWall(WallBase, metaclass=WallEnum, ID=187, NAME="Sandstone Wall"):
    COLOR = ColorRGB(h="#A8603B")


class Wall188(WallBase, metaclass=WallEnum, ID=188, NAME="Wall 188"):
    COLOR = ColorRGB(h="#523F50")


class Wall189(WallBase, metaclass=WallEnum, ID=189, NAME="Wall 189"):
    COLOR = ColorRGB(h="#41334D")


class Wall190(WallBase, metaclass=WallEnum, ID=190, NAME="Wall 190"):
    COLOR = ColorRGB(h="#3E3A51")


class Wall191(WallBase, metaclass=WallEnum, ID=191, NAME="Wall 191"):
    COLOR = ColorRGB(h="#5E4364")


class Wall192(WallBase, metaclass=WallEnum, ID=192, NAME="Wall 192"):
    COLOR = ColorRGB(h="#904334")


class Wall193(WallBase, metaclass=WallEnum, ID=193, NAME="Wall 193"):
    COLOR = ColorRGB(h="#4F1317")


class Wall194(WallBase, metaclass=WallEnum, ID=194, NAME="Wall 194"):
    COLOR = ColorRGB(h="#2F0A0C")


class Wall195(WallBase, metaclass=WallEnum, ID=195, NAME="Wall 195"):
    COLOR = ColorRGB(h="#792A2F")


class Wall196(WallBase, metaclass=WallEnum, ID=196, NAME="Wall 196"):
    COLOR = ColorRGB(h="#70503E")


class Wall197(WallBase, metaclass=WallEnum, ID=197, NAME="Wall 197"):
    COLOR = ColorRGB(h="#7F5E4C")


class Wall198(WallBase, metaclass=WallEnum, ID=198, NAME="Wall 198"):
    COLOR = ColorRGB(h="#614333")


class Wall199(WallBase, metaclass=WallEnum, ID=199, NAME="Wall 199"):
    COLOR = ColorRGB(h="#70503E")


class Wall200(WallBase, metaclass=WallEnum, ID=200, NAME="Wall 200"):
    COLOR = ColorRGB(h="#553952")


class Wall201(WallBase, metaclass=WallEnum, ID=201, NAME="Wall 201"):
    COLOR = ColorRGB(h="#7B6474")


class Wall202(WallBase, metaclass=WallEnum, ID=202, NAME="Wall 202"):
    COLOR = ColorRGB(h="#A7307E")


class Wall203(WallBase, metaclass=WallEnum, ID=203, NAME="Wall 203"):
    COLOR = ColorRGB(h="#96407E")


class Wall204(WallBase, metaclass=WallEnum, ID=204, NAME="Wall 204"):
    COLOR = ColorRGB(h="#53311E")


class Wall205(WallBase, metaclass=WallEnum, ID=205, NAME="Wall 205"):
    COLOR = ColorRGB(h="#5F7652")


class Wall206(WallBase, metaclass=WallEnum, ID=206, NAME="Wall 206"):
    COLOR = ColorRGB(h="#464541")


class Wall207(WallBase, metaclass=WallEnum, ID=207, NAME="Wall 207"):
    COLOR = ColorRGB(h="#53311E")


class Wall208(WallBase, metaclass=WallEnum, ID=208, NAME="Wall 208"):
    COLOR = ColorRGB(h="#3E3D3C")


class Wall209(WallBase, metaclass=WallEnum, ID=209, NAME="Wall 209"):
    COLOR = ColorRGB(h="#554246")


class Wall210(WallBase, metaclass=WallEnum, ID=210, NAME="Wall 210"):
    COLOR = ColorRGB(h="#393434")


class Wall211(WallBase, metaclass=WallEnum, ID=211, NAME="Wall 211"):
    COLOR = ColorRGB(h="#58433B")


class Wall212(WallBase, metaclass=WallEnum, ID=212, NAME="Wall 212"):
    COLOR = ColorRGB(h="#585750")


class Wall213(WallBase, metaclass=WallEnum, ID=213, NAME="Wall 213"):
    COLOR = ColorRGB(h="#383735")


class Wall214(WallBase, metaclass=WallEnum, ID=214, NAME="Wall 214"):
    COLOR = ColorRGB(h="#4C343C")


class Wall215(WallBase, metaclass=WallEnum, ID=215, NAME="Wall 215"):
    COLOR = ColorRGB(h="#524A4D")


class HardenedSandWall(WallBase, metaclass=WallEnum, ID=216, NAME="Hardened Sand Wall"):
    COLOR = ColorRGB(h="#B97F3B")


class CorruptHardenedSandWall(WallBase, metaclass=WallEnum, ID=217, NAME="Corrupt Hardened Sand Wall"):
    COLOR = ColorRGB(h="#463F5E")


class CrimsonHardenedSandWall(WallBase, metaclass=WallEnum, ID=218, NAME="Crimson Hardened Sand Wall"):
    COLOR = ColorRGB(h="#33332D")


class HallowHardenedSandWall(WallBase, metaclass=WallEnum, ID=219, NAME="Hallow Hardened Sand Wall"):
    COLOR = ColorRGB(h="#72618C")


class CorruptSandstoneWall(WallBase, metaclass=WallEnum, ID=220, NAME="Corrupt Sandstone Wall"):
    COLOR = ColorRGB(h="#53356A")


class CrimsonSandstoneWall(WallBase, metaclass=WallEnum, ID=221, NAME="Crimson Sandstone Wall"):
    COLOR = ColorRGB(h="#56372F")


class HallowSandstoneWall(WallBase, metaclass=WallEnum, ID=222, NAME="Hallow Sandstone Wall"):
    COLOR = ColorRGB(h="#3E4765")


class DesertFossilWall(WallBase, metaclass=WallEnum, ID=223, NAME="Desert Fossil Wall"):
    COLOR = ColorRGB(h="#572612")


class LunarBrickWall(WallBase, metaclass=WallEnum, ID=224, NAME="Lunar Brick Wall"):
    COLOR = ColorRGB(h="#262424")


class CogWall(WallBase, metaclass=WallEnum, ID=225, NAME="CogWall"):
    pass


class SandFall(WallBase, metaclass=WallEnum, ID=226, NAME="SandFall"):
    pass


class SnowFall(WallBase, metaclass=WallEnum, ID=227, NAME="SnowFall"):
    pass


class SillyBalloonPinkWall(WallBase, metaclass=WallEnum, ID=228, NAME="SillyBalloonPinkWall"):
    pass


class SillyBalloonPurpleWall(WallBase, metaclass=WallEnum, ID=229, NAME="SillyBalloonPurpleWall"):
    pass


class SillyBalloonGreenWall(WallBase, metaclass=WallEnum, ID=230, NAME="SillyBalloonGreenWall"):
    pass


class IronBrickWall(WallBase, metaclass=WallEnum, ID=231, NAME="IronBrick"):
    pass


class LeadBrickWall(WallBase, metaclass=WallEnum, ID=232, NAME="LeadBrick"):
    pass


class LesionBlockWall(WallBase, metaclass=WallEnum, ID=233, NAME="LesionBlock"):
    pass


class CrimstoneBrickWall(WallBase, metaclass=WallEnum, ID=234, NAME="CrimstoneBrick"):
    pass


class SmoothSandstoneWall(WallBase, metaclass=WallEnum, ID=235, NAME="SmoothSandstone"):
    pass


class Spider(WallBase, metaclass=WallEnum, ID=236, NAME="Spider"):
    pass


class SolarBrickWall(WallBase, metaclass=WallEnum, ID=237, NAME="SolarBrick"):
    pass


class VortexBrickWall(WallBase, metaclass=WallEnum, ID=238, NAME="VortexBrick"):
    pass


class NebulaBrickWall(WallBase, metaclass=WallEnum, ID=239, NAME="NebulaBrick"):
    pass


class StardustBrickWall(WallBase, metaclass=WallEnum, ID=240, NAME="StardustBrick"):
    pass


class OrangeStainedGlass(WallBase, metaclass=WallEnum, ID=241, NAME="OrangeStainedGlass"):
    pass


class GoldStarryGlassWall(WallBase, metaclass=WallEnum, ID=242, NAME="GoldStarryGlassWall"):
    pass


class BlueStarryGlassWall(WallBase, metaclass=WallEnum, ID=243, NAME="BlueStarryGlassWall"):
    pass


class LivingWoodUnsafe(WallBase, metaclass=WallEnum, ID=244, NAME="LivingWoodUnsafe"):
    pass


class WroughtIronFence(WallBase, metaclass=WallEnum, ID=245, NAME="WroughtIronFence"):
    pass


class EbonstoneEcho(WallBase, metaclass=WallEnum, ID=246, NAME="EbonstoneEcho"):
    pass


class MudWallEcho(WallBase, metaclass=WallEnum, ID=247, NAME="MudWallEcho"):
    pass


class PearlstoneEcho(WallBase, metaclass=WallEnum, ID=248, NAME="PearlstoneEcho"):
    pass


class SnowWallEcho(WallBase, metaclass=WallEnum, ID=249, NAME="SnowWallEcho"):
    pass


class AmethystEcho(WallBase, metaclass=WallEnum, ID=250, NAME="AmethystEcho"):
    pass


class TopazEcho(WallBase, metaclass=WallEnum, ID=251, NAME="TopazEcho"):
    pass


class SapphireEcho(WallBase, metaclass=WallEnum, ID=252, NAME="SapphireEcho"):
    pass


class EmeraldEcho(WallBase, metaclass=WallEnum, ID=253, NAME="EmeraldEcho"):
    pass


class RubyEcho(WallBase, metaclass=WallEnum, ID=254, NAME="RubyEcho"):
    pass


class DiamondEcho(WallBase, metaclass=WallEnum, ID=255, NAME="DiamondEcho"):
    pass


class Cave1Echo(WallBase, metaclass=WallEnum, ID=256, NAME="Cave1Echo"):
    pass


class Cave2Echo(WallBase, metaclass=WallEnum, ID=257, NAME="Cave2Echo"):
    pass


class Cave3Echo(WallBase, metaclass=WallEnum, ID=258, NAME="Cave3Echo"):
    pass


class Cave4Echo(WallBase, metaclass=WallEnum, ID=259, NAME="Cave4Echo"):
    pass


class Cave5Echo(WallBase, metaclass=WallEnum, ID=260, NAME="Cave5Echo"):
    pass


class Cave6Echo(WallBase, metaclass=WallEnum, ID=261, NAME="Cave6Echo"):
    pass


class Cave7Echo(WallBase, metaclass=WallEnum, ID=262, NAME="Cave7Echo"):
    pass


class SpiderEcho(WallBase, metaclass=WallEnum, ID=263, NAME="SpiderEcho"):
    pass


class CorruptGrassEcho(WallBase, metaclass=WallEnum, ID=264, NAME="CorruptGrassEcho"):
    pass


class HallowedGrassEcho(WallBase, metaclass=WallEnum, ID=265, NAME="HallowedGrassEcho"):
    pass


class IceEcho(WallBase, metaclass=WallEnum, ID=266, NAME="IceEcho"):
    pass


class ObsidianBackEcho(WallBase, metaclass=WallEnum, ID=267, NAME="ObsidianBackEcho"):
    pass


class CrimsonGrassEcho(WallBase, metaclass=WallEnum, ID=268, NAME="CrimsonGrassEcho"):
    pass


class CrimstoneEcho(WallBase, metaclass=WallEnum, ID=269, NAME="CrimstoneEcho"):
    pass


class CaveWall1Echo(WallBase, metaclass=WallEnum, ID=270, NAME="CaveWall1Echo"):
    pass


class CaveWall2Echo(WallBase, metaclass=WallEnum, ID=271, NAME="CaveWall2Echo"):
    pass


class MarbleEchoUnused(WallBase, metaclass=WallEnum, ID=272, NAME="MarbleEchoUnused"):
    pass


class GraniteEchoUnused(WallBase, metaclass=WallEnum, ID=273, NAME="GraniteEchoUnused"):
    pass


class Cave8Echo(WallBase, metaclass=WallEnum, ID=274, NAME="Cave8Echo"):
    pass


class SandstoneEcho(WallBase, metaclass=WallEnum, ID=275, NAME="SandstoneEcho"):
    pass


class Corruption1Echo(WallBase, metaclass=WallEnum, ID=276, NAME="Corruption1Echo"):
    pass


class Corruption2Echo(WallBase, metaclass=WallEnum, ID=277, NAME="Corruption2Echo"):
    pass


class Corruption3Echo(WallBase, metaclass=WallEnum, ID=278, NAME="Corruption3Echo"):
    pass


class Corruption4Echo(WallBase, metaclass=WallEnum, ID=279, NAME="Corruption4Echo"):
    pass


class Crimson1Echo(WallBase, metaclass=WallEnum, ID=280, NAME="Crimson1Echo"):
    pass


class Crimson2Echo(WallBase, metaclass=WallEnum, ID=281, NAME="Crimson2Echo"):
    pass


class Crimson3Echo(WallBase, metaclass=WallEnum, ID=282, NAME="Crimson3Echo"):
    pass


class Crimson4Echo(WallBase, metaclass=WallEnum, ID=283, NAME="Crimson4Echo"):
    pass


class Dirt1Echo(WallBase, metaclass=WallEnum, ID=284, NAME="Dirt1Echo"):
    pass


class Dirt2Echo(WallBase, metaclass=WallEnum, ID=285, NAME="Dirt2Echo"):
    pass


class Dirt3Echo(WallBase, metaclass=WallEnum, ID=286, NAME="Dirt3Echo"):
    pass


class Dirt4Echo(WallBase, metaclass=WallEnum, ID=287, NAME="Dirt4Echo"):
    pass


class Hallow1Echo(WallBase, metaclass=WallEnum, ID=288, NAME="Hallow1Echo"):
    pass


class Hallow2Echo(WallBase, metaclass=WallEnum, ID=289, NAME="Hallow2Echo"):
    pass


class Hallow3Echo(WallBase, metaclass=WallEnum, ID=290, NAME="Hallow3Echo"):
    pass


class Hallow4Echo(WallBase, metaclass=WallEnum, ID=291, NAME="Hallow4Echo"):
    pass


class Jungle1Echo(WallBase, metaclass=WallEnum, ID=292, NAME="Jungle1Echo"):
    pass


class Jungle2Echo(WallBase, metaclass=WallEnum, ID=293, NAME="Jungle2Echo"):
    pass


class Jungle3Echo(WallBase, metaclass=WallEnum, ID=294, NAME="Jungle3Echo"):
    pass


class Jungle4Echo(WallBase, metaclass=WallEnum, ID=295, NAME="Jungle4Echo"):
    pass


class Lava1Echo(WallBase, metaclass=WallEnum, ID=296, NAME="Lava1Echo"):
    pass


class Lava2Echo(WallBase, metaclass=WallEnum, ID=297, NAME="Lava2Echo"):
    pass


class Lava3Echo(WallBase, metaclass=WallEnum, ID=298, NAME="Lava3Echo"):
    pass


class Lava4Echo(WallBase, metaclass=WallEnum, ID=299, NAME="Lava4Echo"):
    pass


class Rocks1Echo(WallBase, metaclass=WallEnum, ID=300, NAME="Rocks1Echo"):
    pass


class Rocks2Echo(WallBase, metaclass=WallEnum, ID=301, NAME="Rocks2Echo"):
    pass


class Rocks3Echo(WallBase, metaclass=WallEnum, ID=302, NAME="Rocks3Echo"):
    pass


class Rocks4Echo(WallBase, metaclass=WallEnum, ID=303, NAME="Rocks4Echo"):
    pass


class HardenedSandEcho(WallBase, metaclass=WallEnum, ID=304, NAME="HardenedSandEcho"):
    pass


class CorruptHardenedSandEcho(WallBase, metaclass=WallEnum, ID=305, NAME="CorruptHardenedSandEcho"):
    pass


class CrimsonHardenedSandEcho(WallBase, metaclass=WallEnum, ID=306, NAME="CrimsonHardenedSandEcho"):
    pass


class HallowHardenedSandEcho(WallBase, metaclass=WallEnum, ID=307, NAME="HallowHardenedSandEcho"):
    pass


class CorruptSandstoneEcho(WallBase, metaclass=WallEnum, ID=308, NAME="CorruptSandstoneEcho"):
    pass


class CrimsonSandstoneEcho(WallBase, metaclass=WallEnum, ID=309, NAME="CrimsonSandstoneEcho"):
    pass


class HallowSandstoneEcho(WallBase, metaclass=WallEnum, ID=310, NAME="HallowSandstoneEcho"):
    pass


class DesertFossilEcho(WallBase, metaclass=WallEnum, ID=311, NAME="DesertFossilEcho"):
    pass


class BambooBlockWall(WallBase, metaclass=WallEnum, ID=312, NAME="BambooBlockWall"):
    pass


class LargeBambooBlockWall(WallBase, metaclass=WallEnum, ID=313, NAME="LargeBambooBlockWall"):
    pass


class AmberStoneWallEcho(WallBase, metaclass=WallEnum, ID=314, NAME="AmberStoneWallEcho"):
    pass


class BambooFence(WallBase, metaclass=WallEnum, ID=315, NAME="BambooFence"):
    pass


class AshWoodWall(WallBase, metaclass=WallEnum, ID=316, NAME="AshWood"):
    pass


class AshWoodFence(WallBase, metaclass=WallEnum, ID=317, NAME="AshWoodFence"):
    pass


class EchoWall(WallBase, metaclass=WallEnum, ID=318, NAME="EchoWall"):
    pass


class ReefWall(WallBase, metaclass=WallEnum, ID=319, NAME="ReefWall"):
    pass


class PoopWall(WallBase, metaclass=WallEnum, ID=320, NAME="PoopWall"):
    pass


class ShimmerBlockWall(WallBase, metaclass=WallEnum, ID=321, NAME="ShimmerBlockWall"):
    pass


class ShimmerBrickWall(WallBase, metaclass=WallEnum, ID=322, NAME="ShimmerBrickWall"):
    pass


class LunarRustBrickWall(WallBase, metaclass=WallEnum, ID=323, NAME="LunarRustBrickWall"):
    pass


class DarkCelestialBrickWall(WallBase, metaclass=WallEnum, ID=324, NAME="DarkCelestialBrickWall"):
    pass


class AstraBrickWall(WallBase, metaclass=WallEnum, ID=325, NAME="AstraBrickWall"):
    pass


class CosmicEmberBrickWall(WallBase, metaclass=WallEnum, ID=326, NAME="CosmicEmberBrickWall"):
    pass


class CryocoreBrickWall(WallBase, metaclass=WallEnum, ID=327, NAME="CryocoreBrickWall"):
    pass


class MercuryBrickWall(WallBase, metaclass=WallEnum, ID=328, NAME="MercuryBrickWall"):
    pass


class StarRoyaleBrickWall(WallBase, metaclass=WallEnum, ID=329, NAME="StarRoyaleBrickWall"):
    pass


class HeavenforgeBrickWall(WallBase, metaclass=WallEnum, ID=330, NAME="HeavenforgeBrickWall"):
    pass


class AncientBlueBrickWall(WallBase, metaclass=WallEnum, ID=331, NAME="AncientBlueBrickWall"):
    pass


class AncientGreenBrickWall(WallBase, metaclass=WallEnum, ID=332, NAME="AncientGreenBrickWall"):
    pass


class AncientPinkBrickWall(WallBase, metaclass=WallEnum, ID=333, NAME="AncientPinkBrickWall"):
    pass


class AncientGoldBrickWall(WallBase, metaclass=WallEnum, ID=334, NAME="AncientGoldBrickWall"):
    pass


class AncientSilverBrickWall(WallBase, metaclass=WallEnum, ID=335, NAME="AncientSilverBrickWall"):
    pass


class AncientCopperBrickWall(WallBase, metaclass=WallEnum, ID=336, NAME="AncientCopperBrickWall"):
    pass


class AncientObsidianBrickWall(WallBase, metaclass=WallEnum, ID=337, NAME="AncientObsidianBrickWall"):
    pass


class AncientHellstoneBrickWall(WallBase, metaclass=WallEnum, ID=338, NAME="AncientHellstoneBrickWall"):
    pass


class AncientCobaltBrickWall(WallBase, metaclass=WallEnum, ID=339, NAME="AncientCobaltBrickWall"):
    pass


class AncientMythrilBrickWall(WallBase, metaclass=WallEnum, ID=340, NAME="AncientMythrilBrickWall"):
    pass


class LavaMossBlockWall(WallBase, metaclass=WallEnum, ID=341, NAME="LavaMossBlockWall"):
    pass


class ArgonMossBlockWall(WallBase, metaclass=WallEnum, ID=342, NAME="ArgonMossBlockWall"):
    pass


class KryptonMossBlockWall(WallBase, metaclass=WallEnum, ID=343, NAME="KryptonMossBlockWall"):
    pass


class XenonMossBlockWall(WallBase, metaclass=WallEnum, ID=344, NAME="XenonMossBlockWall"):
    pass


class VioletMossBlockWall(WallBase, metaclass=WallEnum, ID=345, NAME="VioletMossBlockWall"):
    pass


class RainbowMossBlockWall(WallBase, metaclass=WallEnum, ID=346, NAME="RainbowMossBlockWall"):
    pass


class ShimmerfallWall(WallBase, metaclass=WallEnum, ID=347, NAME="Shimmerfall"):
    pass


class FallenStarWall(WallBase, metaclass=WallEnum, ID=348, NAME="FallenStarWall"):
    pass


class StoneUnsafe(WallBase, metaclass=WallEnum, ID=349, NAME="StoneUnsafe"):
    pass


class UnbreakableBlockWall(WallBase, metaclass=WallEnum, ID=350, NAME="UnbreakableBlockWall"):
    pass


class FeywoodWall(WallBase, metaclass=WallEnum, ID=351, NAME="FeywoodWall"):
    pass


class HallowedBrickWall(WallBase, metaclass=WallEnum, ID=352, NAME="HallowedBrickWall"):
    pass


class PineTreeBlockWall(WallBase, metaclass=WallEnum, ID=353, NAME="PineTreeBlockWall"):
    pass


class EasterBlockWall(WallBase, metaclass=WallEnum, ID=354, NAME="EasterBlockWall"):
    pass


class GothicBrickWall(WallBase, metaclass=WallEnum, ID=355, NAME="GothicBrickWall"):
    pass


class FlinxFurBlockWall(WallBase, metaclass=WallEnum, ID=356, NAME="FlinxFurBlockWall"):
    pass


class JellyfishBlockWall(WallBase, metaclass=WallEnum, ID=357, NAME="JellyfishBlockWall"):
    pass


class PineWoodBlockWall(WallBase, metaclass=WallEnum, ID=358, NAME="PineWoodBlockWall"):
    pass


class HarpyBlockWall(WallBase, metaclass=WallEnum, ID=359, NAME="HarpyBlockWall"):
    pass


class MoonplateBlockWall(WallBase, metaclass=WallEnum, ID=360, NAME="MoonplateBlockWall"):
    pass


class LibrarianBlockWall(WallBase, metaclass=WallEnum, ID=361, NAME="LibrarianBlockWall"):
    pass


class SpikeBlockWall(WallBase, metaclass=WallEnum, ID=362, NAME="SpikeBlockWall"):
    pass


class OfficeBlockWall(WallBase, metaclass=WallEnum, ID=363, NAME="OfficeBlockWall"):
    pass


class ForbiddenBlockWall(WallBase, metaclass=WallEnum, ID=364, NAME="ForbiddenBlockWall"):
    pass


class WaterBlockWall(WallBase, metaclass=WallEnum, ID=365, NAME="WaterBlockWall"):
    pass


class BoulderBlockWall(WallBase, metaclass=WallEnum, ID=366, NAME="BoulderBlockWall"):
    pass


__all__ = (
    "StoneWall",
    "DirtWall",
    "StoneWallWall",
    "WoodWall",
    "GrayBrickWall",
    "RedBrickWall",
    "BlueBrickWall",
    "GreenBrickWall",
    "PinkBrickWall",
    "GoldBrickWall",
    "SilverBrickWall",
    "CopperBrickWall",
    "HellstoneBrickWall",
    "ObsidianWall",
    "MudWall",
    "DirtWallWall",
    "BlueBrickWallWall",
    "GreenBrickWallWall",
    "PinkBrickWallWall",
    "ObsidianBrickWall",
    "GlassWall",
    "PearlstoneBrickWall",
    "IridescentBrickWall",
    "MudstoneBrickWall",
    "CobaltBrickWall",
    "MythrilBrickWall",
    "PlankedWall",
    "PearlstoneWall",
    "CandyCaneWall",
    "GreenCandyCaneWall",
    "SnowBrickWall",
    "AdamantiteBeamWall",
    "DemoniteBrickWall",
    "SandstoneBrickWall",
    "EbonstoneBrickWall",
    "RedStuccoWall",
    "YellowStuccoWall",
    "GreenStuccoWall",
    "GrayStuccoWall",
    "SnowWall",
    "EbonwoodWall",
    "RichMahoganyWall",
    "PearlwoodWall",
    "RainbowBrickWall",
    "TinBrickWall",
    "TungstenBrickWall",
    "PlatinumBrickWall",
    "AmethystWall",
    "TopazWall",
    "SapphireWall",
    "EmeraldWall",
    "RubyWall",
    "DiamondWall",
    "MossWall",
    "GreenMossWall",
    "RedMossWall",
    "BlueMossWall",
    "PurpleMossWall",
    "RockyDirtWall",
    "LivingLeafWall",
    "RockWall",
    "SpiderCaveWall",
    "ShrubWall",
    "ShrubWallWall",
    "ShrubWall2",
    "GrassWall",
    "JungleWall",
    "FlowerWall",
    "ShrubWall3",
    "ShrubWall4",
    "IceWall",
    "CactusWall",
    "CloudWall",
    "MushroomWall",
    "BoneBlockWall",
    "SlimeBlockWall",
    "FleshBlockWall",
    "LivingWoodWall",
    "CaveWall",
    "MushroomWallWall",
    "ClayWall",
    "DiscWall",
    "HellstoneWall",
    "IceBrickWall",
    "ShadewoodWall",
    "HiveWall",
    "LihzahrdBrickWall",
    "PurpleStainedGlass",
    "YellowStainedGlass",
    "BlueStainedGlass",
    "GreenStainedGlass",
    "RedStainedGlass",
    "MulticoloredStainedGlass",
    "SmallBlueBrickWall",
    "BlueBlockWall",
    "PinkBlockWall",
    "SmallPinkBrickWall",
    "SmallGreenBrickWall",
    "GreenBlockWall",
    "BlueSlabWall",
    "BlueTiledWall",
    "PinkSlabWall",
    "PinkTiledWall",
    "GreenSlabWall",
    "GreenTiledWall",
    "WoodenFence",
    "LeadFence",
    "HiveWallWall",
    "PalladiumColumnWall",
    "BubblegumBlockWall",
    "TitanstoneBlockWall",
    "LihzahrdBrickWallWall",
    "PumpkinWall",
    "HayWall",
    "SpookyWoodWall",
    "ChristmasTreeWallpaper",
    "OrnamentWallpaper",
    "CandyCaneWallpaper",
    "FestiveWallpaper",
    "StarsWallpaper",
    "SquigglesWallpaper",
    "SnowflakeWallpaper",
    "KrampusHornWallpaper",
    "BluegreenWallpaper",
    "GrinchFingerWallpaper",
    "FancyGreyWallpaper",
    "IceFloeWallpaper",
    "MusicWallpaper",
    "PurpleRainWallpaper",
    "RainbowWallpaper",
    "SparkleStoneWallpaper",
    "StarlitHeavenWallpaper",
    "BubbleWallpaper",
    "CopperPipeWallpaper",
    "DuckyWallpaper",
    "WaterfallWall",
    "LavafallWall",
    "EbonwoodFence",
    "RichMahoganyFence",
    "PearlwoodFence",
    "ShadewoodFence",
    "WhiteDynastyWall",
    "BlueDynastyWall",
    "ArcaneRuneWall",
    "IronFence",
    "CopperPlatingWall",
    "StoneSlabWall",
    "Sail",
    "BorealWoodWall",
    "BorealwoodFence",
    "PalmWoodWall",
    "PalmWoodFence",
    "AmberGemsparkWall",
    "AmethystGemsparkWall",
    "DiamondGemsparkWall",
    "EmeraldGemsparkWall",
    "OfflineAmberGemsparkWall",
    "OfflineAmethystGemsparkWall",
    "OfflineDiamondGemsparkWall",
    "OfflineEmeraldGemsparkWall",
    "OfflineRubyGemsparkWall",
    "OfflineSapphireGemsparkWall",
    "OfflineTopazGemsparkWall",
    "RubyGemsparkWall",
    "SapphireGemsparkWall",
    "TopazGemsparkWall",
    "TinPlatingWall",
    "ConfettiWall",
    "MidnightConfettiWall",
    "Wall170",
    "Wall171",
    "HoneyfallWall",
    "ChlorophyteBrickWall",
    "CrimtaneBrickWall",
    "ShroomitePlatingWall",
    "MartianConduitWall",
    "HellstoneBrickWallWall",
    "MarbleWall",
    "MarbleBlockWall",
    "GraniteWall",
    "GraniteBlockWall",
    "MeteoriteBrickWall",
    "MarbleWallWall",
    "GraniteWallWall",
    "Wall185",
    "CrystalWall",
    "SandstoneWall",
    "Wall188",
    "Wall189",
    "Wall190",
    "Wall191",
    "Wall192",
    "Wall193",
    "Wall194",
    "Wall195",
    "Wall196",
    "Wall197",
    "Wall198",
    "Wall199",
    "Wall200",
    "Wall201",
    "Wall202",
    "Wall203",
    "Wall204",
    "Wall205",
    "Wall206",
    "Wall207",
    "Wall208",
    "Wall209",
    "Wall210",
    "Wall211",
    "Wall212",
    "Wall213",
    "Wall214",
    "Wall215",
    "HardenedSandWall",
    "CorruptHardenedSandWall",
    "CrimsonHardenedSandWall",
    "HallowHardenedSandWall",
    "CorruptSandstoneWall",
    "CrimsonSandstoneWall",
    "HallowSandstoneWall",
    "DesertFossilWall",
    "LunarBrickWall",
    "CogWall",
    "SandFall",
    "SnowFall",
    "SillyBalloonPinkWall",
    "SillyBalloonPurpleWall",
    "SillyBalloonGreenWall",
    "IronBrickWall",
    "LeadBrickWall",
    "LesionBlockWall",
    "CrimstoneBrickWall",
    "SmoothSandstoneWall",
    "Spider",
    "SolarBrickWall",
    "VortexBrickWall",
    "NebulaBrickWall",
    "StardustBrickWall",
    "OrangeStainedGlass",
    "GoldStarryGlassWall",
    "BlueStarryGlassWall",
    "LivingWoodUnsafe",
    "WroughtIronFence",
    "EbonstoneEcho",
    "MudWallEcho",
    "PearlstoneEcho",
    "SnowWallEcho",
    "AmethystEcho",
    "TopazEcho",
    "SapphireEcho",
    "EmeraldEcho",
    "RubyEcho",
    "DiamondEcho",
    "Cave1Echo",
    "Cave2Echo",
    "Cave3Echo",
    "Cave4Echo",
    "Cave5Echo",
    "Cave6Echo",
    "Cave7Echo",
    "SpiderEcho",
    "CorruptGrassEcho",
    "HallowedGrassEcho",
    "IceEcho",
    "ObsidianBackEcho",
    "CrimsonGrassEcho",
    "CrimstoneEcho",
    "CaveWall1Echo",
    "CaveWall2Echo",
    "MarbleEchoUnused",
    "GraniteEchoUnused",
    "Cave8Echo",
    "SandstoneEcho",
    "Corruption1Echo",
    "Corruption2Echo",
    "Corruption3Echo",
    "Corruption4Echo",
    "Crimson1Echo",
    "Crimson2Echo",
    "Crimson3Echo",
    "Crimson4Echo",
    "Dirt1Echo",
    "Dirt2Echo",
    "Dirt3Echo",
    "Dirt4Echo",
    "Hallow1Echo",
    "Hallow2Echo",
    "Hallow3Echo",
    "Hallow4Echo",
    "Jungle1Echo",
    "Jungle2Echo",
    "Jungle3Echo",
    "Jungle4Echo",
    "Lava1Echo",
    "Lava2Echo",
    "Lava3Echo",
    "Lava4Echo",
    "Rocks1Echo",
    "Rocks2Echo",
    "Rocks3Echo",
    "Rocks4Echo",
    "HardenedSandEcho",
    "CorruptHardenedSandEcho",
    "CrimsonHardenedSandEcho",
    "HallowHardenedSandEcho",
    "CorruptSandstoneEcho",
    "CrimsonSandstoneEcho",
    "HallowSandstoneEcho",
    "DesertFossilEcho",
    "BambooBlockWall",
    "LargeBambooBlockWall",
    "AmberStoneWallEcho",
    "BambooFence",
    "AshWoodWall",
    "AshWoodFence",
    "EchoWall",
    "ReefWall",
    "PoopWall",
    "ShimmerBlockWall",
    "ShimmerBrickWall",
    "LunarRustBrickWall",
    "DarkCelestialBrickWall",
    "AstraBrickWall",
    "CosmicEmberBrickWall",
    "CryocoreBrickWall",
    "MercuryBrickWall",
    "StarRoyaleBrickWall",
    "HeavenforgeBrickWall",
    "AncientBlueBrickWall",
    "AncientGreenBrickWall",
    "AncientPinkBrickWall",
    "AncientGoldBrickWall",
    "AncientSilverBrickWall",
    "AncientCopperBrickWall",
    "AncientObsidianBrickWall",
    "AncientHellstoneBrickWall",
    "AncientCobaltBrickWall",
    "AncientMythrilBrickWall",
    "LavaMossBlockWall",
    "ArgonMossBlockWall",
    "KryptonMossBlockWall",
    "XenonMossBlockWall",
    "VioletMossBlockWall",
    "RainbowMossBlockWall",
    "ShimmerfallWall",
    "FallenStarWall",
    "StoneUnsafe",
    "UnbreakableBlockWall",
    "FeywoodWall",
    "HallowedBrickWall",
    "PineTreeBlockWall",
    "EasterBlockWall",
    "GothicBrickWall",
    "FlinxFurBlockWall",
    "JellyfishBlockWall",
    "PineWoodBlockWall",
    "HarpyBlockWall",
    "MoonplateBlockWall",
    "LibrarianBlockWall",
    "SpikeBlockWall",
    "OfficeBlockWall",
    "ForbiddenBlockWall",
    "WaterBlockWall",
    "BoulderBlockWall",
)
