import logging

from bs4 import Tag, ResultSet, BeautifulSoup

from lihzahrd._generate.class_name_factory import ClassNameFactory

log = logging.getLogger(__name__)


class TilesGenerator:
    """
    Class that reads a ``tiles.xml`` file `from TerraMap`_ and outputs Python code using :mod:`lihzahrd` structures to represent it.

    .. _from TerraMap: https://github.com/TerraMap/windows/blob/master/Data/tiles.xml
    """

    def __init__(self, soup: BeautifulSoup):
        """
        Create a new instance of the generator, given an XML tiles document processed with :mod:`BeautifulSoup4` (:mod:`lxml`).

        :param soup: The processed XML tiles document.
        """
        self.factory: ClassNameFactory = ClassNameFactory()
        tiles = self._tiles_element(soup)
        self.tile: ResultSet[Tag] = self._tile_elements(tiles)
        self.wall: ResultSet[Tag] = self._wall_elements(tiles)
        self.prefix: ResultSet[Tag] = self._prefix_elements(tiles)
        self.item: ResultSet[Tag] = self._item_elements(tiles)
        self.global_: ResultSet[Tag] = self._global_elements(tiles)
        self.npc: ResultSet[Tag] = self._npc_elements(tiles)

    @classmethod
    def _tiles_element(cls, soup: BeautifulSoup) -> Tag:
        """
        :param soup: The processed XML tiles document to search for the tag in.
        :return: The ``<tiles>`` element of the ``soup``.
        :raise ValueError: If no ``<tiles>`` element exists in the document.
        """
        log.debug("Finding <tiles> element...")
        if result := soup.find("tiles", recursive=False):
            return result
        raise ValueError("Could not find a `tiles` element.")

    @classmethod
    def _tile_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<tile>`` elements that are direct children of the :meth:`._tiles_element`.
        """
        log.debug("Finding <tile> elements...")
        return tiles.find_all("tile", recursive=False)

    @classmethod
    def _var_elements(cls, element: Tag) -> ResultSet[Tag]:
        """
        :param element: A single element, returned by either :meth:`._tile_elements` or :meth:`._var_elements` itself.
        :return: All the ``<var>`` elements that are direct children of ``tile``.
        """
        log.debug("Finding <var> elements...")
        return element.find_all("var", recursive=False)

    @classmethod
    def _wall_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<wall>`` elements that are direct children of ``tiles``.
        """
        log.debug("Finding <wall> elements...")
        return tiles.find_all("wall", recursive=False)

    @classmethod
    def _prefix_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<prefix>`` elements that are direct children of ``tiles``.
        """
        log.debug("Finding <prefix> elements...")
        return tiles.find_all("prefix", recursive=False)

    @classmethod
    def _item_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<item>`` elements that are direct children of ``tiles``.
        """
        log.debug("Finding <item> elements...")
        return tiles.find_all("item", recursive=False)

    @classmethod
    def _global_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<global>`` elements that are direct children of ``tiles``.
        """
        log.debug("Finding <global> elements...")
        return tiles.find_all("global", recursive=False)

    @classmethod
    def _npc_elements(cls, tiles: Tag) -> ResultSet[Tag]:
        """
        :param tiles: The ``<tiles>`` element returned by :meth:`._tiles_element`.
        :return: All the ``<Npc>`` elements that are direct children of ``tiles``.

        .. note::

            ``<Npc>`` has an uppercase N.
        """
        log.debug("Finding <Npc> elements...")
        return tiles.find_all("Npc", recursive=False)

    @staticmethod
    def _generate_module_docstring() -> str:
        log.debug("Generating module docstring...")
        return (
            "# language=rst\n"
            '"""\n'
            ".. note::\n"
            "\n"
            "    This module was partially generated by :class:`lihzahrd._generate.terraria.tiles_generator.TilesGenerator`.\n"
            "\n"
            '"""\n'
            "\n"
        )

    @staticmethod
    def _generate_dunder_all(names) -> str:
        result = []

        result.append("__all__ = (")

        for name in names:
            result.append(f"    {name!r},")

        result.append(")")

        return "\n".join(result) + "\n"

    def generate_blocks(self) -> str:
        """
        Generate the new contents of :mod:`lihzahrd.terraria.data.classmembers.blocks`.

        :returns: The contents, as a :class:`str`.
        """
        log.debug("Generating blocks...")

        result = [
            self._generate_module_docstring(),
            self._generate_blocks_imports(),
        ]

        names = []

        for tile in self.tile:
            name, code = self._generate_block(tile=tile)
            result.append(code)
            names.append(name)

        result.append(self._generate_dunder_all(names))

        return "".join(result)

    @staticmethod
    def _generate_blocks_imports() -> str:
        log.debug("Generating block imports...")
        return (
            "from lihzahrd.terraria.data.frameimportant_variant import FrameImportantVariant\n"
            "from lihzahrd.terraria.data.classmembers.block_base import BlockBase\n"
            "from lihzahrd.terraria.data.classenums.block_enum import BlockEnum\n"
            "from lihzahrd.terraria.utils.structures.color import ColorRGB\n"
            "\n"
            "\n"
        )

    def _generate_block(self, tile: Tag) -> tuple[str, str]:
        log.debug("Generating block...")

        tile_id = tile["num"]
        tile_id = int(tile_id)
        log.debug("Block id is: %r", tile_id)

        tile_name = tile["name"]
        tile_name = str(tile_name)
        log.debug("Block name is: %r", tile_name)

        class_name = self.factory(tile_name, "Block")
        log.debug("Class name is: %r", class_name)

        attributes = self._generate_block_attributes(tile)
        variants = self._generate_block_variants(tile)

        return (
            class_name,
            (
                f"class {class_name!s}(BlockBase, metaclass=BlockEnum, ID={tile_id!r}, NAME={tile_name!r}):\n"
                f"{attributes}\n"
                f"    FRAMEIMPORTANT_VARIANTS = (\n"
                f"{variants}\n"
                f"    )\n"
                f"\n"
                f"\n"
            ),
        )

    @staticmethod
    def _generate_block_attributes(block: Tag) -> str:
        log.debug("Generating block attributes...")

        result = []

        if value := block.get("color"):
            result.append(f"    COLOR = ColorRGB(h={value!r})")
        del value

        if value := block.get("solid"):
            value = bool(int(value))
            result.append(f"    SOLID = {value!r}")
        del value

        if value := block.get("blend"):
            value = bool(int(value))
            result.append(f"    BLEND = {value!r}")
        del value

        if value := block.get("merge"):
            value = bool(int(value))
            result.append(f"    MERGE = {value!r}")
        del value

        if value := block.get("letLight"):
            value = bool(int(value))
            result.append(f"    TRANSPARENT = {value!r}")
        del value

        if value := block.get("isStone"):
            value = bool(int(value))
            result.append(f"    IS_STONE = {value!r}")
        del value

        if value := block.get("isGrass"):
            value = bool(int(value))
            result.append(f"    IS_GRASS = {value!r}")
        del value

        value_r = block.get("lightr")
        value_g = block.get("lightg")
        value_b = block.get("lightb")
        if value_r and value_g and value_b:
            value_r = float(value_r)
            value_g = float(value_g)
            value_b = float(value_b)
            result.append(f"    EMIT_LIGHT_COLOR = ColorRGB(r={value_r!r}, g={value_g!r}, b={value_b!r})")
        del value_r
        del value_g
        del value_b

        if len(result) == 0:
            result.append("    pass")

        return "\n".join(result)

    def _generate_block_variants(self, block: Tag) -> str:
        log.debug("Generating block variants...")

        result = []

        for var in self._var_elements(block):
            result.append("        FrameImportantVariant(")

            if value := var.get("u"):
                value = int(value)
                result.append(f"            eq_u={value!r},")
            del value

            if value := var.get("v"):
                value = int(value)
                result.append(f"            eq_v={value!r},")
            del value

            if value := var.get("minu"):
                value = int(value)
                result.append(f"            min_u={value!r},")
            del value

            if value := var.get("minv"):
                value = int(value)
                result.append(f"            min_v={value!r},")
            del value

            if value := var.get("maxu"):
                value = int(value)
                result.append(f"            max_u={value!r},")
            del value

            if value := var.get("maxv"):
                value = int(value)
                result.append(f"            max_v={value!r},")
            del value

            if value := var.get("name"):
                result.append(f"            name={value!r},")
            del value

            if value := var.get("color"):
                result.append(f"            color=ColorRGB(h={value!r}),")
            del value

            if value := var.get("solid"):
                value = bool(int(value))
                result.append(f"            solid={value!r},")
            del value

            if value := var.get("blend"):
                value = bool(int(value))
                result.append(f"            blend={value!r},")
            del value

            if value := var.get("merge"):
                value = bool(int(value))
                result.append(f"            merge={value!r},")
            del value

            if value := var.get("letLight"):
                value = bool(int(value))
                result.append(f"            transparent={value!r},")
            del value

            if value := var.get("isStone"):
                value = bool(int(value))
                result.append(f"            is_stone={value!r},")
            del value

            if value := var.get("isGrass"):
                value = bool(int(value))
                result.append(f"            is_grass={value!r},")
            del value

            result.append("        ),")

        return "\n".join(result)

    def generate_items(self) -> str:
        """
        Generate the new contents of :mod:`lihzahrd.terraria.data.classmembers.items`.

        :returns: The contents, as a :class:`str`.
        """
        log.debug("Generating items...")

        result = [
            self._generate_module_docstring(),
            self.generate_items_imports(),
        ]

        names = []

        for item in self.item:
            name, code = self.generate_item(item=item)
            result.append(code)
            names.append(name)

        result.append(self._generate_dunder_all(names))

        return "".join(result)

    @staticmethod
    def generate_items_imports() -> str:
        log.debug("Generating items imports...")
        return (
            "from lihzahrd.terraria.data.classmembers.item_base import ItemBase\n"
            "from lihzahrd.terraria.data.classenums.item_enum import ItemEnum\n"
            "\n"
            "\n"
        )

    def generate_item(self, item: Tag) -> tuple[str, str]:
        log.debug("Generating item...")

        item_id = item.get("num")
        item_id = int(item_id)
        log.debug("Item id is: %r", item_id)

        item_name = item.get("name")
        log.debug("Item name is: %r", item_name)

        class_name = self.factory(item_name, "Item")

        return (
            class_name,
            (
                f"class {class_name}(ItemBase, metaclass=ItemEnum, ID={item_id!r}, NAME={item_name!r}):\n"
                f"    pass\n"
                f"\n"
                f"\n"
            ),
        )

    def generate_npcs(self) -> str:
        """
        Generate the new contents of :mod:`lihzahrd.terraria.data.classmembers.npcs`.

        :returns: The contents, as a :class:`str`.
        """
        log.debug("Generating npcs...")

        result = [
            self._generate_module_docstring(),
            self._generate_npcs_imports(),
        ]

        names = []

        for npc in self.npc:
            name, code = self._generate_npc(npc=npc)
            result.append(code)
            names.append(name)

        result.append(self._generate_dunder_all(names))

        return "".join(result)

    @staticmethod
    def _generate_npcs_imports() -> str:
        log.debug("Generating npcs imports...")
        return (
            "from lihzahrd.terraria.data.classmembers.npc_base import NPCBase\n"
            "from lihzahrd.terraria.data.classenums.npc_enum import NPCEnum\n"
            "\n"
            "\n"
        )

    def _generate_npc(self, npc: Tag) -> tuple[str, str]:
        log.debug("Generating npc...")

        npc_id = npc.get("Id")
        npc_id = int(npc_id)
        log.debug("NPC id is: %r", npc_id)

        npc_name = npc.get("Name")
        log.debug("NPC name is: %r", npc_name)

        class_name = self.factory(npc_name, "NPC")

        return (
            class_name,
            (
                f"class {class_name}(NPCBase, metaclass=NPCEnum, ID={npc_id!r}, JOB={npc_name!r}):\n"
                f"    pass\n"
                f"\n"
                f"\n"
            ),
        )

    def generate_prefixes(self) -> str:
        """
        Generate the new contents of :mod:`lihzahrd.terraria.data.classmembers.prefixes`.

        :returns: The contents, as a :class:`str`.
        """
        log.debug("Generating prefixes...")

        result = [
            self._generate_module_docstring(),
            self._generate_prefixes_imports(),
        ]

        names = []

        for prefix in self.prefix:
            name, code = self._generate_prefix(prefix=prefix)
            result.append(code)
            names.append(name)

        result.append(self._generate_dunder_all(names))

        return "".join(result)

    @staticmethod
    def _generate_prefixes_imports() -> str:
        log.debug("Generating prefix imports...")
        return (
            "from lihzahrd.terraria.data.classmembers.prefix_base import PrefixBase\n"
            "from lihzahrd.terraria.data.classenums.prefix_enum import PrefixEnum\n"
            "\n"
            "\n"
        )

    def _generate_prefix(self, prefix: Tag) -> tuple[str, str]:
        log.debug("Generating prefix...")

        prefix_id = prefix.get("num")
        prefix_id = int(prefix_id)
        log.debug("Prefix id is: %r", prefix_id)

        prefix_name = prefix.get("name")
        log.debug("Prefix name is: %r", prefix_name)

        class_name = self.factory(prefix_name, "Prefix")

        return (
            class_name,
            (
                f"class {class_name}(PrefixBase, metaclass=PrefixEnum, ID={prefix_id!r}, NAME={prefix_name!r}):\n"
                f"    pass\n"
                f"\n"
                f"\n"
            ),
        )

    def generate_walls(self) -> str:
        """
        Generate the new contents of :mod:`lihzahrd.terraria.data.classmembers.walls`.

        :returns: The contents, as a :class:`str`.
        """
        log.debug("Generating walls...")

        result = [
            self._generate_module_docstring(),
            self._generate_walls_imports(),
        ]

        names = []

        for wall in self.wall:
            name, code = self._generate_wall(wall=wall)
            result.append(code)
            names.append(name)

        result.append(self._generate_dunder_all(names))

        return "".join(result)

    @staticmethod
    def _generate_walls_imports() -> str:
        log.debug("Generating wall imports...")
        return (
            "from lihzahrd.terraria.data.classmembers.wall_base import WallBase\n"
            "from lihzahrd.terraria.data.classenums.wall_enum import WallEnum\n"
            "from lihzahrd.terraria.utils.structures.color import ColorRGB\n"
            "\n"
            "\n"
        )

    def _generate_wall(self, wall: Tag) -> tuple[str, str]:
        log.debug("Generating wall...")

        wall_id = wall.get("num")
        wall_id = int(wall_id)
        log.debug("Prefix id is: %r", wall_id)

        wall_name = wall.get("name")
        log.debug("Prefix name is: %r", wall_name)

        class_name = self.factory(wall_name, "Wall")

        attributes = self._generate_wall_attributes(wall=wall)

        return (
            class_name,
            (
                f"class {class_name}(WallBase, metaclass=WallEnum, ID={wall_id!r}, NAME={wall_name!r}):\n"
                f"{attributes}\n"
                f"\n"
                f"\n"
            ),
        )

    @staticmethod
    def _generate_wall_attributes(wall: Tag) -> str:
        log.debug("Generating wall attributes...")

        result = []

        if value := wall.get("color"):
            result.append(f"    COLOR = ColorRGB(h={value!r})")
        del value

        if value := wall.get("blend"):
            value = int(value)
            result.append(f"    BLEND = {value!r}")
        del value

        if len(result) == 0:
            result.append(f"    pass")

        return "\n".join(result)


__all__ = ("TilesGenerator",)
